### ISSUE TITLE
How validate translatable fields of Knp Doctrine Behaviors strategy

### ISSUE THREAD

**Issue by kvaje** [a2lix/TranslationFormBundle#104]
Hello,

I use Symfony 2.4, a2lix Translation bundle 2.0 and Knp Doctrine behaviors 1.0 translatable strategy.

How can validate tranlatable fields? If I use Assert in SiteTranslatabe it does not work.

Example:

namespace net\xxxBundle\Entity;

use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
- @ORM\Entity(repositoryClass="Pnet\xxxBundle\Entity\Repository\SiteRepository")
- @UniqueEntity("host", message="site.host.unique")
- @Gedmo\Tree(type="nested")
- @ORM\Table(name="site")
- @ORM\HasLifecycleCallbacks
  */
  class Site
  {
  use ORMBehaviors\Translatable\Translatable;   
  
  /**
  - @ORM\Id
  - @ORM\Column(type="integer")
  - @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;
  
  /**
  - @ORM\Column(type="string", length=40, unique=true)
  - @Assert\NotBlank(message="site.host.notBlank")
  - @Assert\Length(max = "40", maxMessage = "site.host.maxLength")
    */  
    protected $host;

...............................

namespace net\xxxBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
- @ORM\Entity
  */
  class SiteTranslation
  {
  use ORMBehaviors\Translatable\Translation;
  
  /**
  - @ORM\Column(type="string")
  - @Assert\NotBlank(message="site.name.notBlank")
  - @Assert\Length(max = "60", maxMessage = "site.name.maxLength")
    */ 
    protected $name; 
  
  /**
  - @ORM\Column(type="string")
  - @Assert\NotBlank(message="site.title.notBlank")
  - @Assert\Length(max = "100", maxMessage = "site.title.maxLength")
    */  
    protected $title;  
  
  /**
  - @ORM\Column(type="string")
  - @Assert\NotBlank(message="site.title.notBlank")
  - @Assert\Length(max = "200", maxMessage = "site.longTitle.maxLength")
    */ 
    protected $longTitle;
  
  /**
  - @ORM\Column(type="string", nullable=true)
  - @Assert\Length(max = "250", maxMessage = "site.keywords.maxLength")
    */  
    protected $keywords;
  
  /**
  - @ORM\Column(type="string", nullable=true)
  - @Assert\Length(max = "500", maxMessage = "site.description.maxLength")
    */  
    protected $description;

.................

SiteType:
.........................
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'net\xxxBundle\Entity\Site',
            'translation_domain' => 'site',
        ));
    }
...........................

Assert works only for Site, but not works for SiteTranslation

**Comment by tamcy** [comment]
I just encountered a strange behavior with form validation which looks the same as what @kvaje encountered - when all fields of a locale (e.g. en) is blank, validation won't work. It turns out the reason is that the locale (en in my case) must be in "required_locales" for validation to work in all-empty case. I changed `config.yml` from

```yml
a2lix_translation_form:
    required_locales: [fr]
```
to
```yml
a2lix_translation_form:
    required_locales: [en, fr]
```
and validation to en worked.

Hope it may help someone.
