### ISSUE TITLE
Ability to use collection form field type with a2lix_translationsForms

### ISSUE THREAD

**Issue by peschee** [a2lix/TranslationFormBundle#133]
Hi

I have a entity with documents (uploaded files) attached to it. These documents should be translatable into multiple languages. I followed the steps mentioned on the Symfony (2.4) docs and in the issues here.

In the ```buildForm``` method of my entity form type, I have added the entity documents as follows:

```php
$builder->add('documents', 'a2lix_translationsForms', array(
    'form_type' => DocumentType(),
    'required' => false
));
```

This works as expected. I can add one document in all languages necessary. However, now I have trouble making this work with multiple documents per entity (and translation). From what I saw, currently ```a2lix_translationsForms``` does not work with the ```collection``` form type? Is there a way to add multiple documents per language?

Any help or hints is appreciated.

**Comment by peschee** [comment]
@webda2l Fixed by a commit?

**Comment by webda2l** [comment]
Close because seems outdated issue. Maybe you should give a try to the 3.x version.
And you have https://github.com/a2lix/Demo for some example.

**Comment by peschee** [comment]
Allright, thanks for the info.
