### ISSUE TITLE
Display or hide translatable field (display => true or false)

### ISSUE THREAD

**Issue by kvaje** [a2lix/TranslationFormBundle#134]
Hello,

I'm creating form dynamicly and I would like to show or hide some translatable fields, depends on user properties. I have used display (<i>'display' => false</i>) attribute and field is hidden but if i set <i>'display' => true</i> i got an error <i>"The option "display" does not exist. Known options are ..."</i>

Example:

<pre>
$introductionVisible = $properties['introductionVisible'] == 'true' ? 'true' : 'false';

     $builder->add('translations', 'a2lix_translations', array(
            'fields' => array(                      // [optional] Manual configuration of fields to display and options. If not specified, all translatable fields will be display, and options will be auto-detected
                'title' => array(
                    'label' => 'form.content.title',              // [optional] Custom label. Ucfirst, otherwise
                    'field_type' => 'textarea',           // [optional] Custom type
                    'trim' => true,
                ), 
                'introduction' => array(
                    'label' => 'form.introduction.text',              // [optional] Custom label. Ucfirst, otherwise
                    'field_type' => 'ckeditor',           // [optional] Custom type
                    'display' => $introductionVisible
                )
        )); 
</pre>

Is it possible to solve problem with <i>'display' => true</i> value?

**Comment by icedevelopment** [comment]
I have the same problem, you can reproduce this simply by setting 'display' => true on a field.
The issue seems to be in TranslationForm#getFieldsOptions().
You can probably reopen the issue.

Thanks
