### ISSUE TITLE
Multiple a2lix_translations_widget in the same page

### ISSUE THREAD

**Issue by Prometee** [a2lix/TranslationFormBundle#147]
Hi,

There is a tiny bug when multiple instances of a2lix_translations_widget are display in the same page.
When you click on a tab, all tabs in the same page are switched.
I add the id of the widget to the tab class and data-target to avoid this.

 data-target=".a2lix_translationsFields-{{ locale }}"
to
data-target=".a2lix_translationsFields-{{ id }}-{{ locale }}"

And
class="a2lix_translationsFields-{{ locale }}
to
class="a2lix_translationsFields-{{ id }}-{{ locale }}

Thank you for your work guys !

**Comment by ksn135** [comment]
:+1:  for using id in data-target
