### ISSUE TITLE
How to get the translated fields

### ISSUE THREAD

**Issue by Mondane** [a2lix/TranslationFormBundle#150]
I want to do some extra checks if a translated field exists in the form, ie. it isn't excluded. How can I get the keys for the fields that are to be rendered by the TranslationFormBundle? I managed to get the keys for all translatable fields using the first locale in the translations, see:

```twig
{{ dump(form.translations|first|keys) }}
```

but I don't see how to get the list that is returned by A2lix\TranslationFormBundle\TranslationForm\TranslationForm->getTranslationFields()

**Comment by webda2l** [comment]
````
{% for translationsFields in form.translations %}
    {{ dump(translationsFields ) }}
{% endfor %}
````
?
