### ISSUE TITLE
Too many DB queries for more locales

### ISSUE THREAD

**Issue by PriaBrock** [a2lix/TranslationFormBundle#167]
Hi,

I'm not sure if this is related with your bundle or is it something in Symfony, but I have a site with 13 locales and this is where the DB queries are rapidly growing for every translated Entity form field.
It seems that Symfony are getting the options for the correct entity class by retrieving the locales first.

SELECT 
  t0.title AS title1, 
  t0.id AS id2, 
  t0.locale AS locale3, 
  t0.translatable_id AS translatable_id4, 
  t5.icon_code AS icon_code6, 
  t5.internal_name AS internal_name7, 
  t5.icon_url AS icon_url8, 
  t5.id AS id9, 
  t5.icon_image AS icon_image10 
FROM 
  my_bundle_icon_translation t0 
  LEFT JOIN my_bundle_icon t5 ON t0.translatable_id = t5.id 
WHERE 
  t0.translatable_id = ?

And this is done for every record in the table my_bundle_icon. And this is only oone relation. So it created about 40 queries only to retrive options for one entity.  If I have more, it will grow much more. It it possible to change this behaviour? As it should load the whole repository and the translations with it by one query?

**Comment by markitosgv** [comment]
Hi @PriaBrock ,

With this PR #169 i think your problem will be solve.

**Comment by webda2l** [comment]
Hi,

As https://github.com/a2lix/TranslationFormBundle/issues/167#issuecomment-75527535 said
