### ISSUE TITLE
__toString() locale problem

### ISSUE THREAD

**Issue by wow** [a2lix/TranslationFormBundle#168]
Hello,

I'm using the a2lix TranslationFormBundle with SonataAdmin
it's very useful thank you so much.
but i have a little problem.

when i try to use __toString() method on base Entity, it returns second language name.

for example;

my CategoryEntity:
class Category
{
    use Id;
    use A2lixI18n\ORM\Util\Translatable;

   /**
     * @Assert\Valid
     */
    protected $translations;

    public function __construct()
    {
        $this->translations = new ArrayCollection;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

-- CategoryTranslationEntity

class CategoryTranslation implements A2lixI18n\Interfaces\OneLocaleInterface
{
    use A2lixI18n\ORM\Util\Translation;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=64)
     *
     */
    protected $name;

    /**
     * Set name
     *
     * @param string $name
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    public function __toString()
    {
        return $this->getName();
    }
}

----------------------------------------------

it's perfectly working with create, edit and list. (it gives me the main language data)
but,
somehow I need to use __toString() method on SanataAdmin from CategoryEntity
but when i call category on Sonata, A2lix gives me the second language data.

is there any mistake that i have?
or is it a little bug? :)

Thanks,
ilham

**Comment by webda2l** [comment]
Hello, hope you found solution, hard to say was wrong with current information, I close.
