### ISSUE TITLE
Mapping error when default locale is not filled

### ISSUE THREAD

**Issue by PriaBrock** [a2lix/TranslationFormBundle#170]
Hi,

I've encounter problem when the default locale translation is not filled (as sometimes it really should be) and there is a problem, because than I've a mapping error when symfony is trying to map translatedEntity which is represented by empty array instead of object with no values.

For example I have a gallery with translated names (title) and than I want to associate some images to it. If there is a default locale translation of this entity, everything is OK, but if there is any other one and no default locale, than the mapping error will appear.

Because it gets an array of two items, one is the, for example, en translation object and second is the default locale, which is empty array.

Is this something that your bundle is responsible for or is it the KNP doctrine behaviour problem?

**Comment by webda2l** [comment]
Hi,

Try to set the query_builder option in your a2lix_translatedEntity field

````
 'query_builder' => function (\Doctrine\ORM\EntityRepository $er) {
 return $er->createQueryBuilder('e')
 ->select('e, t')
 ->leftJoin('e.translations', 't');
 },
````

**Comment by PriaBrock** [comment]
Hi,

no it doesn't help. I think that some time before (I'm using this bundle for about 3 months), if there was no translations for the entity for actual locale, it simply displays empty string as option, but now it doesn't work.

**Comment by PriaBrock** [comment]
Hi,

I've found the problem. Don't know if there a mistake somewhere or in doc, but according the doc you should use this settings for TranslatedEntity type of form field.

$builder->add('medias', 'a2lix_translatedEntity', array(
    'class' => 'A2lix\DemoTranslationBundle\Entity\Media',   // [6 - Mandatory]
    'translation_property' => 'text',                        // [7 - Mandatory]
    'multiple' => true,                                      // [8]
));

But this won't work. You have to change the 'translation_property' to 'property'. Now it works like a charm.
