### ISSUE TITLE
sonata_type_collection in tab with 'edit' => 'inline' and error : no exclamation mark

### ISSUE THREAD

**Issue by fredpeaks** [a2lix/TranslationFormBundle#175]
When I have an error in a sonata_type_collection sub-form and this sub-form is in a tab and I use the ```'edit' => 'inline'``` option, the exclamation mark is not visible on the first tab with error.
I think this is because the "show_form_first_tab_with_errors" js function search for at least an element with the "sonata-ba-field-error" class inside the tab content to show the exclamation mark. And with the ```'edit' => 'inline'``` option the form fields with errors are not rendered with the  "sonata-ba-field-error" class when there are errors.

**Comment by webda2l** [comment]
Fixed by https://github.com/a2lix/TranslationFormBundle/pull/182
