### ISSUE TITLE
Deprecated code for Symfony 2.7 -> 3.0

### ISSUE THREAD

**Issue by markitosgv** [a2lix/TranslationFormBundle#176]
Hi! I´m using this amazing bundle and recently im testing Symfony 2.7-Beta1
There are some functions like setDefaultOptions in Form Classes that are going to be deprecated in Symfony 3.0

Maybe is a good idea do a new branch to adapt these type of changes , what do you think?

**Comment by webda2l** [comment]
Hi, thanks.
Yes good idea, I've created a 3.x branch with 2.7 & 3.0 target.
I will try to find time in next 30days to work on it.

Feel free to do PR on it too.

**Comment by andrzejdziekonski** [comment]
Hi, 
what's the status of 3.0 branch? I installed it with minimum-stability dev and after installation i received an error: 
```
"a2lix_translation_form.default.listener.translations" has a dependency on a non-existent service "a2lix_auto_form.default.manipulator". 
```
so i guess it's not working yet. Is there any hope it's gona be usable soon :) ?

**Comment by webda2l** [comment]
@andrzejdziekonski No progress currently, I need to find some time for it.

**Comment by giovkanata** [comment]
@webda2l Hi, any news about the status of 3.0 branch?

**Comment by webda2l** [comment]
Still some work for 3.x but already in use in https://github.com/a2lix/Demo/tree/translation-form-3.x-with-sf-3.x
