### ISSUE TITLE
a2lix_translations in sonata, rich text option?

### ISSUE THREAD

**Issue by ferris32** [a2lix/TranslationFormBundle#177]
I've set up TranslationFormBundle with Prezent which works perfect with the locale tabs.
Now there is an issue providing the user with translatable rich text input field.

Is there a way to inject sonata_formatter_type into the fields options of the translation?
Or another way to create rich text translations?

This is the call now:

				->add('translations', 'a2lix_translations', 
						array(
							'locales' => array('en', 'nl'), 
							'required_locales' => array('en'),
							'label' => false,
							'fields' => array( 
								'title' => array(),
								'content' => array(
									'field_type' => 'textarea', 
									'label' => 'Description'
								))))

Otherwise I'll have to go for another solution...

**Comment by webda2l** [comment]
For https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/configuration.md by example, something like :

````
            ->add('translations', 'a2lix_translations', 
                    array(
                        'locales' => array('en', 'nl'), 
                        'required_locales' => array('en'),
                        'label' => false,
                        'fields' => array( 
                            'title' => array(),
                            'content' => array(
                                'field_type' => 'ckeditor'
                                'config_name' => 'my_config',
                                'label' => 'Description'
                            ))))
````
should be ok.

For sonata_formatter_type, it'll need a custom overwrite of this form type to work I think.

**Comment by ferris32** [comment]
Easy enough!
That's a quick and good solution for now.

Still a lot to learn about Sonata but it is a great framework
