### ISSUE TITLE
The form type translated Entity ignores provided query builder

### ISSUE THREAD

**Issue by PriaBrock** [a2lix/TranslationFormBundle#178]
Hi,

 I have this query:

            'query_builder' => function( EntityRepository $er){
                $qb = $er->createQueryBuilder('category')
                    ->select('category, translations')
                    ->leftJoin('category.translations','translations');
                $qb->where($qb->expr()->isNull('category.deletedAt'));

                return $qb;
            },

For entity field, it's OK and works as a charm, but for the a2lix_translatedEntity field, it won't. It simply ignores the rules, that the deleted ones shouldn't be at the select options. For this behavior, I'm using the KNP Soft Deletable behavior.

Thank you for any advice

**Comment by webda2l** [comment]
Hi,

Can't say. Need deeper debugging. Never meet problem with custom query_builder. Maybe your deletedAt was on translation side, and so:

            $qb->where($qb->expr()->isNull('translation .deletedAt'));
