### ISSUE TITLE
A2lix Form Translation Bundle adding new language spl_object_hash()

### ISSUE THREAD

**Issue by kmehmety** [a2lix/TranslationFormBundle#185]
I am already using A2lix Form Translation Bundle with KNP Doctrine Behaviors Bundle or A2lixI18N. Everything was work perfectly until i added new language.

I added new language and i am taking this error:

Warning: spl_object_hash() expects parameter 1 to be object, null given

My config looks like:

a2lix_translation_form:
    locale_provider: default
    locales: [en, ru, fr]
    default_locale: en
    required_locales: [en]
    manager_registry: doctrine

i tried A2lixI8nBundle but result is the same.

**Comment by kmehmety** [comment]
Anyone? Is anyone was experienced this issue?

**Comment by CharlyPoppins** [comment]
Maybe it's related to this : https://github.com/KnpLabs/DoctrineBehaviors/issues/259
The problem seems to be a required locale.

**Comment by webda2l** [comment]
Too little information to give answer and maybe already fix by new versions, I close
