### ISSUE TITLE
Notice: Undefined index: translationClass

### ISSUE THREAD

**Issue by grekpg** [a2lix/TranslationFormBundle#186]
Hi i have error whe try use this bundle 

http://stackoverflow.com/questions/30978554/undefined-index-translationclass-in-gedmotranslationform

**Comment by webda2l** [comment]
Solved?

**Comment by grekpg** [comment]
no but i dont have time to investigate so use other translations

**Comment by webda2l** [comment]
Ok I close, version 1.x is old now, prefer most recent version.
