### ISSUE TITLE
Add full support to gedmo extensions

### ISSUE THREAD

**Issue by nicodmf** [a2lix/TranslationFormBundle#187]
As the gedmo extension 2.4 is out. This excellent bundle should rely on this central library.

A first try is here #180 

@a2lix this bundle is very important in the translation process with symfony, can you give us an advice on his evolution?

And thanks for this great work.

**Comment by behramcelen** [comment]
:+1:

**Comment by leechao** [comment]
:+1: Moreover, the gedmo translation documentation points toward a2lixTranslationFormBundle for translations field type. It is kind of disappointing when you set up gedmo extensions and see way after that a2lixTranslationFormBundle isn't quite compatible yet.

**Comment by leechao** [comment]
Well, seems like the 2.4 version of Gedmo isn't quite what was expected : https://github.com/a2lix/TranslationFormBundle/issues/184

**Comment by nicodmf** [comment]
@webda2l Even if you dislike gedmo 2.4 implementation, gedmo is a standard in facts, and many projexts integrate it for many purpose. I think this is the good idea to implement it. I think too you are one of the better expert with php translations and you are certainly one of the better developper to help the gedmo extensions to progress on the translation part.

**Comment by picks44** [comment]
Would be nice yes.

**Comment by jblanchon** [comment]
Hello,
What status of the compatibility of gedmo 2.4 and A2lixTranslationBundle 2.* ?

**Comment by mkalisz77** [comment]
Hi,
Anybody run this nice bundle with Gedmo Translations? Is it work ?

**Comment by behramcelen** [comment]
Hi @mkalisz77 i tried a lot but i can't. If you can use this https://github.com/Prezent/doctrine-translatable translatable extension a2lix/TranslationFormBundle is working perfectly. You can check an working example from https://github.com/ojs/ojs/blob/master/composer.json#L51-L52.

**Comment by mkalisz77** [comment]
Did you use Personal Translations ?
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#personal-translations
for a2lix or default behaviour of Gedemo Translatable ?

**Comment by behramcelen** [comment]
@mkalisz77 if you check fully there is big logic difference between stof/StofDoctrineExtensionsBundle and Prezent/doctrine-translatable. If you use Prezent/doctrine-translatable supports personal translations fully. 

You can inspect below related links for usage;
 - https://github.com/ojs/ojs/blob/master/src/Ojs/JournalBundle/Entity/ArticleTypes.php#L94
 - https://github.com/ojs/ojs/blob/master/src/Ojs/JournalBundle/Entity/ArticleTypesTranslation.php
 - https://github.com/ojs/ojs/blob/master/src/Ojs/JournalBundle/Entity/ArticleTypesTranslation.php#L15
 - https://github.com/ojs/ojs/blob/master/src/Ojs/JournalBundle/Resources/config/doctrine/ArticleTypesTranslation.orm.yml

Note: And also we use gedmo extensions but disabled gedmo translatable extension for using Prezent/doctrine-translatable

**Comment by mkalisz77** [comment]
Is this Prezent/doctrine-translatable bundle compatible with Symfony 3.

**Comment by kenchopa** [comment]
any progress on this on ?

**Comment by behramcelen** [comment]
@mkalisz77 we are using dev-master and our symfony 2.7 i didn 't tested exactly but i do not think it will symfony 3 brokes.

https://github.com/ojs/ojs/blob/master/composer.json#L52
And @mkalisz77 i certainly not suggest using gedmo translatable logic is so wrong. With gedmo i struggled so much :weary:

**Comment by mkalisz77** [comment]
Thank you,
I think about Prezent translatable or KnpDoctrineExtensions. I've resigned from using Gedmo Translatable. Knp seems to be actively maintained and Prezent is much lighter to implement Translatables.

**Comment by webda2l** [comment]
Prefer KnpDoctrineExtensions (https://packagist.org/packages/knplabs/doctrine-behaviors, well more popular) than Prezent (https://packagist.org/packages/prezent/doctrine-translatable)
