### ISSUE TITLE
Different locales for CMS and website doesn't display active tab

### ISSUE THREAD

**Issue by stefantalen** [a2lix/TranslationFormBundle#189]
I've come across this with a custom CMS that sets the session locale when a user logges in (based on its preferences)

These locales are nl, de, en and are being used for the fixed translation of our modules.

On the website however the locales that are being used are for example nl_NL and en_GB so content can be filled in.

The problem is, because the session locale is "nl" but the form tab is "nl_NL" there is no tab active.

Is there a specific reason the locale of the request is being assumed as default selection?

Why not set the first tab as active?

So instead of this check:

    {% if app.request.locale == locale %}

It'll be:

    {% if loop.first %}

I've updated this in my own template so it works but was wondering why this isn't default behaviour.

**Comment by webda2l** [comment]
With right locales configuration for a2lix_translation_form, with ````locales: [nl_NL, en_GB]````, no problem about me
