### ISSUE TITLE
Tab selection not 100% working

### ISSUE THREAD

**Issue by fkrauthan** [a2lix/TranslationFormBundle#193]
I have a collection of translatable entities on one of my forms. Rendering works correct but if I click on another language on one of my tabs ALL translatable entities change there text fields to the other languages local. But the tab bar indicator for the other fields stays at the old local.

So either if I change the local at one tab bar it should just change the text fields there (my preference) or you should change the active tab marker too.

**Comment by fkrauthan** [comment]
I just saw there is already a pull request #190 for this issue.

**Comment by webda2l** [comment]
https://github.com/a2lix/TranslationFormBundle/pull/190 merged
