### ISSUE TITLE
Making a A2lix translation field required in the front end in a Symfony form

### ISSUE THREAD

**Issue by crmpicco** [a2lix/TranslationFormBundle#202]
Is there a way to make a A2lix translation field required and validated through the front-end in a Symfony form? I have tried adding a property of `presentation` and `translations` to my `validation.yml` file, but to no avail.

I find that when I don't enter anything in the translation field the form doesn't submit, but nothing happens. No FE or BE error.

My form:

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('translations', 'a2lix_translationsForms', array(
                'form_type' => new CourseGuideTranslationType($this->dataClass . 'Translation', $this->validationGroups),
                'label'     => 'crmpicco.course_guide.name',
                'required'  => true
            ))
            ->add('name', 'text');
    }

In `validation.yml`:

    CRMPicco\GolfBundle\Entity\CourseGuide:
        properties:
            name:
                - NotBlank: ~

`CourseGuideTranslationType.php`:

    class CourseGuideTranslationType extends AbstractResourceType
    {
        /**
         * {@inheritdoc}
         */
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('presentation', 'text', array(
                    'required' => true,
                    'label'    => false,
                ))
            ;
        }
    
        /**
         * {@inheritdoc}
         */
        public function getName()
        {
            return 'crmpicco_course_guide_translation';
        }
    }

**Comment by cengizhancaliskan** [comment]
Hi,

Add in your entity;

use Symfony\Component\Validator\Constraints as Assert;
......
/**
     * @Assert\Valid
     */
    protected $translations;

**Comment by webda2l** [comment]
As https://github.com/a2lix/TranslationFormBundle/issues/202#issuecomment-158052341 said.

**Comment by neonovic** [comment]
Is this really working in all cases? Because when I submit all translatable fields as empty, I get no validation checkings. As I have posted here: http://stackoverflow.com/questions/42130782/a2lix-translations-validation-not-working-when-all-fields-are-submited-as-empty

**Comment by Sentence** [comment]
It works for me, i tried some workaround and this is the best case. (Also i know that not really clean and documented... :D)

**Comment by pdias** [comment]
I also had the same problem https://github.com/a2lix/TranslationFormBundle/issues/202#issuecomment-278590322 _(no validation check when all fields are empty_), i change the method **submit** in **TranslationsListener**.

```
public function submit(FormEvent $event): void
    {
        $data = $event->getData();
        $form = $event->getForm();  //new
        $formOptions = $form->getConfig()->getOptions(); //new
        foreach ($data as $locale => $translation) {
            // Remove useless Translation object
            if ((method_exists($translation, 'isEmpty') && $translation->isEmpty() && !\in_array($locale, $formOptions['required_locales'], false)) //Knp ---> changed
                || empty($translation)
            ) {
                $data->removeElement($translation);
                continue;
            }
            $translation->setLocale($locale);
        }
    }
```

I use Sf4 and this solved my problem.
