### ISSUE TITLE
Error using A2lix as an embedded form

### ISSUE THREAD

**Issue by anacicconi** [a2lix/TranslationFormBundle#207]
I'm using A2lix Translation Form Bundle and Doctrine Behaviors Translatable in a project where I have two entities: company and files. Company has some translatable fields so I have a CompanyTranslations Entity for that. One company can have one file so Company and file are mapped with an OneToOne unidirectional reference. The company file is translatable so the property is in the CompanyTranslation file.

CompanyTranslation:

	class CompanyTranslation
	{
	    use ORMBehaviors\Translatable\Translation;
	
	    /**
	     * @ORM\OneToOne(targetEntity="File", cascade={"persist"})
	     * @ORM\JoinColumn(name="translatable_file_id", referencedColumnName="id")
	     * @Assert\Valid()
	     * @Assert\Type(type="MyApp\CoreBundle\Entity\File")
	     **/
	    private $translatableFile;
	
	    /**
	     * Set translatableFile
	     *
	     * @param $translatableFile
	     */
	    public function setTranslatableFile(File $translatableFile = null)
	    {
	        $this->translatableFile = $translatableFile;
	    }
	
	    /**
	     * Get translatableFile
	     *
	     * @return $translatableFile
	     */
	    public function getTranslatableFile()
	    {
	        return $this->translatableFile;
	    }
	}

File:

    class File
	{
	    /**
	     * @var integer
	     *
	     * @ORM\Column(name="id", type="integer")
	     * @ORM\Id
	     * @ORM\GeneratedValue(strategy="AUTO")
	     */
	    protected $id;
	
	    /**
	     * @ORM\Column(type="string", length=255, nullable=true)
	     */
	    public $filePath;
	
	    /**
	     * @Assert\File()
	     */
	    private $file;
	
	    /**
	     * Get id
	     *
	     * @return integer
	     */
	    public function getId()
	    {
	        return $this->id;
	    }
	
	    /**
	     * Set filePath
	     *
	     * @param string $filePath
	     */
	    public function setFilePath($filePath)
	    {
	        $this->filePath = $filePath;
	    }
	
	    /**
	     * Get filePath
	     *
	     * @return string
	     */
	    public function getFilePath()
	    {
	        return $this->filePath;
	    }
	
	    /**
	     * Set file
	     *
	     * @param UploadedFile $file
	     */
	    public function setFile(UploadedFile $file = null)
	    {
	        $this->file = $file;
	    }
	
	    /**
	     * Get file
	     *
	     * @return UploadedFile
	     */
	    public function getFile()
	    {
	        return $this->file;
	    }
	}

File Form Type:

    class FileType extends AbstractType
	{
	    public function buildForm(FormBuilderInterface $builder, array $options)
	    {
	        $builder->add('file', 'file', array(
	            'label' => false
	        ));
	    }
	
	    public function configureOptions(OptionsResolver $resolver)
	    {
	        $resolver->setDefaults(array(
	            'data_class' => 'MyApp\CoreBundle\Entity\File'
	        ));
	    }
	
	    public function getName()
	    {
	        return 'file_form';
	    }
	}

Company Form Type:

    class CompanyType extends AbstractType
	{
	    public function buildForm(FormBuilderInterface $builder, array $options)
	    {
	        $builder
	            ->add('translations', 'a2lix_translationsForms', array(
	                'locales' => $this->languages,
	                'form_type' => new FileType(),
	                'form_options' => array(
	                    'data_class' => 'MyApp\CoreBundle\Entity\File',
	                    'required'      => false,
	                    'validation_groups' => array('file_upload')
	                )
	            ));
	    }

	    public function setDefaultOptions(OptionsResolverInterface $resolver)
	    {
	        parent::setDefaultOptions($resolver);
	
	        $resolver->setDefaults(array(
	            'data_class' => 'MyApp\CoreBundle\Entity\Company'
	        ));
	    }
	}

The error is this one: 

The form's view data is expected to be an instance of class MyApp\CoreBundle\Entity\File, but is an instance of class MyApp\CoreBundle\Entity\CompanyTranslation. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class MyApp\CoreBundle\Entity\CompanyTranslation to an instance of MyApp\CoreBundle\Entity\File.
    
I already set the data_class of the File Type Form and the data_class of the field to null but also to MyApp\CoreBundle\Entity\File. Both send me errors. I don't know what's happening.

Could anyone help?

Thanks!

**Comment by webda2l** [comment]
Hello,

Below, here is a solution that I'have done in a project some time ago.
If you want use the a2lix_translationsForms, you need a locale field in your entity.
In fact if you have a Company entity and want some fields translated, you do a CompanyTranslation for translate theses fields (only simple fields, not Entities as your FileEntity), well configured with Knp or whatever strategy.
If you want a full Entity for different language, you add a locale field inside it and it become a "Localize" entity, as FileLocalize bellow. No strategy needed.
You can combine theses two features too and have a Company with a CompanyTranslation and FileLocalize relations.
For creation/edition, "a2lix_translations" will be use for CompanyTranslation and "a2lix_translationsForms" for FileLocalize 

````
class Company
{
....

    /**
     * @ORM\OneToMany(targetEntity="FileLocalize", mappedBy="company", indexBy="locale", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Assert\Type(type="MyApp\CoreBundle\Entity\FileLocalize")
     **/
    private $files;

    public function __construct()
    {
          $this->files = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getFiles()
    {
        return $this->files;
    }

    public function setFiles(\Doctrine\Common\Collections\ArrayCollection $files)
    {
        $this->files = $files;
        return $this;
    }

    public function addFile(FileLocalize $file)
    {
        if ($file->getFilePath()) {
            $this->getFiles()->set($file->getLocale(), $file);
            $file->setCompany($this);
        }
        return $this;
    }

    public function removeFile(FileLocalize $file)
    {
        $this->files->removeElement($file);
    }

....
}
````

````
class FileLocalize
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $filePath;

    /**
     * @Assert\File()
     */
    private $file;

    /**
     * @ORM\Column(length=10)
     */
    protected $locale;

    /**
     * @var Company $company
     * @ORM\ManyToOne(targetEntity="Company", inversedBy="files")
     */
    protected $company;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set filePath
     *
     * @param string $filePath
     */
    public function setFilePath($filePath)
    {
        $this->filePath = $filePath;
    }

    /**
     * Get filePath
     *
     * @return string
     */
    public function getFilePath()
    {
        return $this->filePath;
    }

    /**
     * Set file
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function getLocale()
    {
        return $this->locale;
    }
    public function setLocale($locale)
    {
        $this->locale = $locale;
        return $this;
    }

    public function getCompany()
    {
        return $this->company;
    }

    public function setCompany(Company $company)
    {
        $this->company = $company;
        return $this;
    }
}
````

````
class FileLocalizeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('file', 'file', array(
            'label' => false
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MyApp\CoreBundle\Entity\File'
        ));
    }

    public function getName()
    {
        return 'file_form';
    }
}
````

````
class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('translations', 'a2lix_translationsForms', array(
                'locales' => $this->languages,
                'form_type' => new FileLocalizeType(),
                'form_options' => array(
                    'data_class' => 'MyApp\CoreBundle\Entity\File',
                    'required'      => false,
                    'validation_groups' => array('file_upload')
                )
            ));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MyApp\CoreBundle\Entity\Company'
        ));
    }
}
````

**Comment by anacicconi** [comment]
Hi @webda2l , thanks for your answer!

I just tried your solution and I still get the error with the data_class:

    The form's view data is expected to be an instance of class MyApp\CoreBundle\Entity\File, but is an instance of class MyApp\CoreBundle\Entity\CompanyTranslation. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class MyApp\CoreBundle\Entity\CompanyTranslation to an instance of MyApp\CoreBundle\Entity\File.

I did exactly what you described and in my CompanyTranslation entity I don't have any relation to the File entity. Do you know what is the problem?

I have also another problem with this solution. First, I wanted the relation between Company and File to be a OneToOne relation. Actually, I can have different properties on Company that are related to File. It already woks for non translatable files like that. I have for example:

    /**
     * @ORM\OneToOne(targetEntity="File", cascade={"persist"})
     * @ORM\JoinColumn(name="first_file_id", referencedColumnName="id")
     * @Assert\Valid()
     * @Assert\Type(type="MyApp\CoreBundle\Entity\File")
     **/
    private $firstFile;

    /**
     * @ORM\OneToOne(targetEntity="File", cascade={"persist"})
     * @ORM\JoinColumn(name="second_file_id", referencedColumnName="id")
     * @Assert\Valid()
     * @Assert\Type(type="MyApp\CoreBundle\Entity\File")
     **/
    private $secondFile;

The second problem is that I want to keep this OneToOne relation unidirectional as I will have many entities related to File. I don't want each time to have a reference to these entities on the File entity.

Is it possible to do that with a2lix_translationsForms?

Thank you!

**Comment by anacicconi** [comment]
And just another question. When using the FileLocalized as you suggested, should I add a trait to it? I mean the traits from Knp\DoctrineBehaviors like use ORMBehaviors\Translatable\Translatable?

**Comment by webda2l** [comment]
Hi,

For the first part,
it's ````data_class => 'MyApp\CoreBundle\Entity\FileLocalize'```` and not ````data_class => 'MyApp\CoreBundle\Entity\FileLocalized'````

===

For the second part, why not think differently, and instead have two differents FileLocalized entities, have only a FilesLocalized entity (or CompanyFilesLocalized or ...) which will have inner $firstFilePath, $firstFile, $secondFilePath, $secondFile, $locale and $company.
If you really don't want keep reference of Company, you will have to come back to the CompanyTranslation solution, well configured with Knp, and directly $firstFilePath, $firstFile, $secondFilePath, $secondFile without kind of File entity. And so use of a2lix_translations instead of a2lix_translationsForms.

**Comment by anacicconi** [comment]
Actually, I just wrote it wrong here. In the code, I tried: 

    data_class => 'MyApp\CoreBundle\Entity\FileLocalize'

I'll think about this other possibilities and I'll let you know. However, I'm still trying to understand why I have this bug with data_class when it should work. If I var_dump $translation, I am sending a FileLocalize object which is the value the program is expecting.

**Comment by anacicconi** [comment]
I found it @webda2l ! I was using the annotation @Assert\Type on my $files property. I don't understand why it doesn't accept it (as the object I send is a FileLocalize entity) and if it is a good idea to remove it but the bug comes from here:

    /**
     * @ORM\OneToMany(targetEntity="FileLocalize", mappedBy="company", indexBy="locale", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Assert\Type(type="MyApp\CoreBundle\Entity\FileLocalize")
     **/
    private $files;

Did you use this Assert when you did this kind of mapping with A2lix Translation Form Bundle?

**Comment by webda2l** [comment]
Ok fine, you're welcome for the help.
I started last week some rethink about this bundle, and hope push some code soon (no date anyway..). I look to manage your case of a CompanyTranslation with a File association. Will see if I have time to finish and its results.

Otherwise, no I'm not sure to already have use @Assert\Type on entity. Only useful if you fill form by script/command. I advice use php native typecast in add/remove function, as ````function addFile(FileLocalize $file)```` however, as always :)

**Comment by anacicconi** [comment]
Cool. Let me know if I can help somehow with this File/Company association. 

For the typecast, I did it too. I use the Assert\Type because it is on Symfony documentation:

http://symfony.com/doc/current/book/forms.html#embedded-forms

But maybe it's not essential.

**Comment by manoj815** [comment]
hi I am beginner in symfony and i am using a2lix transform bundle . i follow the above step to embed media form in form but  how to handle files array collection in controller to add and update .Please help

**Comment by tamert** [comment]
i could not solve a like issue. 
Now, I'm using EasyAdmin, DoctrineBehaviors Translate and A2Lix

My Config YML:
`      form:
        fields:
          - type: 'group'
            css_class: 'col-md-4'
          - { property: 'rank', css_class: 'col-md-12' }
          - { property: 'nfrkeyCount', css_class: 'col-md-12' }
          - { property: 'isVisible', css_class: 'col-md-12' }
          - { property: 'isServerCertified', css_class: 'col-md-12' }
          - type: 'group'
            css_class: 'col-md-8'
          - property: 'translations'
            type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType'
            label: 'global.translations'
            data_class: null
            type_options:
              data_class: null
              required: true
              fields:
                title:
                  label: 'global.title'
                support:
                  label: 'support'
                marketingKickBack:
                  label: 'marketingKickBack'
                body:
                  field_type: 'App\Form\Type\QuillType'
                  label: 'global.body'
`

Have one record showing this error
'
The form's view data is expected to be an instance of class Proxies\__CG__\App\Entity\UserLevelTranslation, but is an instance of class App\Entity\UserLevelTranslation. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class App\Entity\UserLevelTranslation to an instance of Proxies\__CG__\App\Entity\UserLevelTranslation.
'

I tried many ideas but not solved. please help me :)

**Comment by tamert** [comment]
I solved but that is not logic

file : A2lix\TranslationFormBundle\Form\EventListener\TranslationsListener
```php

    private function getTranslationClass(FormInterface $form): string
    {

        do {
                $translatableClass = str_replace("Proxies\__CG__\\", "",  $form->getConfig()->getDataClass());

        } while ((null === $translatableClass) && $form->getConfig()->getInheritData() && (null !== $form = $form->getParent()));
        
        if (method_exists($translatableClass, 'getTranslationEntityClass')) {
            return $translatableClass::getTranslationEntityClass();
        }

        // Gedmo
        if (method_exists($translatableClass, 'getTranslationClass')) {

            return $translatableClass::getTranslationClass();
        }

        return $translatableClass.'Translation';
    }
```
i change this line :)
```php
str_replace("Proxies\__CG__\\", "",  $form->getConfig()->getDataClass());
```

How i disabled Proxies entity ?
