### ISSUE TITLE
Translating entity array values

### ISSUE THREAD

**Issue by ferdynator** [a2lix/TranslationFormBundle#209]
I have an [entity](https://github.com/pagedynamo-cms/PagedynamoAdminBundle/blob/feature/DoctrineBehaviors/Entity/PageBlock.php) with a [translation](https://github.com/pagedynamo-cms/PagedynamoAdminBundle/blob/feature/DoctrineBehaviors/Entity/PageBlockTranslation.php). What I would like to do is to extend the [FormType](https://github.com/pagedynamo-cms/PagedynamoAdminBundle/blob/feature/DoctrineBehaviors/Form/Type/PageBlockTextType.php) to have the attribute `data[content]` as a translated ckeditor form field. 

This is what I came up with so far:

        public function moduleEditAction(Request $request, PageBlock $pageblock)
       {
        // [...]
        $formTransContainer = $this->createFormBuilder();
        $formTransContainer->add(
            'translations',
            'a2lix_translationsForms',
            [
                'attr' => ['class' => 'width-100 translationArea'],
                'label' => false,
                'form_type' => $formType
            ]
        );
        $formTransContainer->setData($pageblock->getData());
        $form = $formTransContainer->getForm();

You can find the Controller [here](https://github.com/pagedynamo-cms/PagedynamoAdminBundle/blob/feature/DoctrineBehaviors/Controller/PageController.php). The result looks OK but stored data is not displayed in the textarea and upon save the `TranslationsFormsListener` fails because it cannot set the locale for an array.

I hope it is clear what I want. Is it possible? Am I going in the totally wrong direction?

**Comment by ferdynator** [comment]
@webda2l any updates on this?

**Comment by webda2l** [comment]
It's a particular case that will not be managed by this bundle.
You should inspired you of TranslationsFormsType & TranslationsFormsListener to do create your own type & listener that work with array.
