### ISSUE TITLE
What is the right way to use A2lix and collection of forms?

### ISSUE THREAD

**Issue by anacicconi** [a2lix/TranslationFormBundle#216]
Hello, 

I'm trying to use a2lix with embedded collection of forms. My form displays well but there's no way to persist my translatable entity to the database. I was wondering if someone has an example that works so I can maybe take some inspiration.

Here is my code:

**class Establishment:**
    
    /**
     * @ORM\OneToMany(targetEntity="EmailDesign", mappedBy="establishment", cascade={"persist"})
     * @Assert\Valid()
     */
    private $emailDesigns;
    
    public function __construct()
    {
        $this->emailDesigns                     = new ArrayCollection();
    }
    
    public function addEmailDesign(EmailDesign $emailDesign)
    {
        $emailDesign->setEstablishment($this);

        $this->emailDesigns->add($emailDesign);
    }

    public function removeEmailDesign(EmailDesign $emailDesign)
    {
        $this->emailDesigns->removeElement($emailDesign);
    }

    public function getEmailDesigns()
    {
        return $this->emailDesigns;
    }
    
**class EmailDesign:**
    
    /**
     * @ORM\ManyToOne(targetEntity="Establishment", inversedBy="emailDesigns", cascade={"persist"})
     * @ORM\JoinColumn(name="establishment_id", referencedColumnName="id")
     * @Assert\Valid()
     */
    private $establishment;
    
    public function setEstablishment($establishment)
    {
        $this->establishment = $establishment;
    }

    public function getEstablishment()
    {
        return $this->establishment;
    }
    
**class EmailDesignType:**
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
	    $builder
	        ->add('type', 'text', array(
	            'required' => true
	        ))
	        ->add('translations', 'a2lix_translations', array(
	            'locales' => $this->languages,
	            'label' => ' ',
	            'fields'    => array(
	                'fromName' => array(
	                    'field_type' => 'text',
	                    'label' => 'establishment.customize.from',
	                    'required' => false,
	                ),
	                'subjectLine' => array(
	                    'field_type' => 'text',
	                    'label' => 'establishment.customize.subject',
	                    'required' => false,
	                ),
	                'bodyText' => array(
	                    'field_type' => 'textarea',
	                    'label' => 'establishment.customize.body',
	                    'required' => false,
	                    "attr" => array('class' => 'tinymce', 'data-theme' => $this->dataTheme)
	                ),
	                'legalNotice' => array(
	                    'field_type' => 'textarea',
	                    'label' => 'establishment.customize.legalnotice',
	                    'required' => false,
	                    "attr" => array('class' => 'tinymce', 'data-theme' => 'email_share')
	                )
	        )));
	}  
	
	public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\MyBundle\Entity\EmailDesign',
            'translation_domain' => 'backoffice'
        ));
    }        
        
**class EstablishmentEmailDesignType:**
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
	    $builder
	        ->add('name', 'text')
	        ->add('emailDesigns', 'collection',
	            array('type' => new EmailDesignType(),
	            'allow_add'    => true,
	            'by_reference' => false,
	            'prototype' => true,
	            'cascade_validation' => true,
	        ));
    }    
        
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\MyBundle\Entity\Establishment',
            'cascade_validation' => true
        ));
    } 
    
**controller:**
    
    public function emailDesignAction(Request $request, Establishment $establishment)
    {
        $em = $this->getDoctrine()->getManager();  
        
        $form = $this->createForm(new EstablishmentEmailDesignType(), $establishment);
        $form->handleRequest($request);
        
        if ($form->isValid()) {
	        $em->persist($establishment);
            $em->flush();
        }   
        
        return array(
            'establishment' => $establishment,
            'form'          => $form->createView(),
        );
    }  
        
**twig:**
    
    <ul class="emailDesigns" data-prototype="{{ form_widget(form.emailDesigns.vars.prototype)|e }}"></ul>    

If I change a Establishment property (like "name" on EstablishmentEmailDesignType), it is persisted. However the fields of EmailDesign are not persisted.

Thanks.

**Comment by webda2l** [comment]
Hi,

Hope you found solution, I close.
