### ISSUE TITLE
I am beginner in symfony2 and I am using a2lix transform bundle. I use separate entity to embed media form in form but how to handle files array collection in controller to add and update? 

### ISSUE THREAD

**Issue by manoj815** [a2lix/TranslationFormBundle#217]
<?php

namespace Application\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * FreemoniAdBanners
 *
 * @ORM\Table(name="freemoni_addbanner")
 * @ORM\Entity(repositoryClass="Application\AdminBundle\Repository\AdBannersRepository")
 * @Gedmo\TranslationEntity(class="AdBannersTranslation")
 * 
 * 
 */
class AdBanners {

    use \A2lix\I18nDoctrineBundle\Doctrine\ORM\Util\Translatable;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="AdBannersTranslation", mappedBy="object", indexBy="locale", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid
     */
    protected $translations;

    /**
     * @ORM\OneToMany(targetEntity="FileLocalize", mappedBy="AdBanners", indexBy="locale", cascade={"all"}, orphanRemoval=true)
     * @Assert\Valid()
     * @Assert\Type(type="Application\AdminBundle\Entity\FileLocalize")
     * */
    public $files;

    /**
     * @var boolean
     *
     * @ORM\Column(name="activeStatus", type="boolean")
     */
    private $activeStatus;

    /**
     * @var boolean
     *
     * @ORM\Column(name="deleteStatus", type="boolean")
     */
    private $deleteStatus;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdDate", type="datetime")
     */
    private $createdDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="modifiedDate", type="datetime")
     */
    private $modifiedDate;

    function __construct() {
        $this->activeStatus = 0;
        $this->deleteStatus = 0;
        $this->createdDate = new \DateTime;
        $this->modifiedDate = new \DateTime;
        $this->translations = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

    public function getId() {
        return $this->id;
    }

    /**
     * Set activeStatus
     *
     * @param boolean $activeStatus
     *
     * @return FreemoniFranchise
     */
    public function setActiveStatus($activeStatus) {
        $this->activeStatus = $activeStatus;

        return $this;
    }

    /**
     * Get activeStatus
     *
     * @return boolean
     */
    public function getActiveStatus() {
        return (boolean) $this->activeStatus;
    }

    /**
     * Set deleteStatus
     *
     * @param boolean $deleteStatus
     *
     * @return FreemoniFranchise
     */
    public function setDeleteStatus($deleteStatus) {
        $this->deleteStatus = $deleteStatus;

        return $this;
    }

    /**
     * Get deleteStatus
     *
     * @return boolean
     */
    public function getDeleteStatus() {
        return $this->deleteStatus;
    }

    /**
     * Set createdDate
     *
     * @param \DateTime $createdDate
     *
     * @return FreemoniFranchise
     */
    public function setCreatedDate($createdDate) {
        $this->createdDate = $createdDate;

        return $this;
    }

    /**
     * Get createdDate
     *
     * @return \DateTime
     */
    public function getCreatedDate() {
        return $this->createdDate;
    }

    /**
     * Set modifiedDate
     *
     * @param \DateTime $modifiedDate
     *
     * @return FreemoniFranchise
     */
    public function setModifiedDate($modifiedDate) {
        $this->modifiedDate = $modifiedDate;

        return $this;
    }

    /**
     * Get modifiedDate
     *
     * @return \DateTime
     */
    public function getModifiedDate() {
        return $this->modifiedDate;
    }

    public function getTranslations() {
        return $this->translations;
    }

    public function getFiles() {
        return $this->files;
    }

    public function setFiles(FileLocalize $files) {
        $this->files = $files;
        return $this;
    }

    public function addFile(FileLocalize $file) {
        if ($file->getFilePath()) {
            $this->getFiles()->set($file->getLocale(), $file);
            $file->setAdBanners($this);
        }
        return $this;
    }

    public function removeFile(FileLocalize $file) {
        $this->files->removeElement($file);
    }

}

<?php

namespace Application\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * FileLocalize
 * @ORM\Entity
 * @ORM\Table(name="file")
 *  
 * 
 * 
 */
class FileLocalize {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $filePath;

    /**

     * @var file $file
     *  
     * @Assert\File(
     *      maxSize = "2M",
     *      mimeTypes = {"image/jpeg", "image/pjpeg", "image/png", "image/x-png", "image/gif"},
     *      mimeTypesMessage = "this image format is unknown",
     *      uploadIniSizeErrorMessage = "The downloaded file is too large",
     *      uploadFormSizeErrorMessage = "The downloaded file is larger than that permitted by the input field of the HTML file",
     *      uploadErrorMessage = "The downloaded file may be transferred for unknown reason",
     *      maxSizeMessage = "The file is too large"
     * )
     */
    protected $file;

    /**
     * @ORM\Column(length=10)
     */
    protected $locale;

    /**
     *  
     * @ORM\ManyToOne(targetEntity="AdBanners", inversedBy="file")
     */
    protected $AdBanners;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set filePath
     *
     * @param string $filePath
     */
    public function setFilePath($filePath) {
        $this->filePath = $filePath;
    }

    /**
     * Get filePath
     *
     * @return string
     */
    public function getFilePath() {
        return $this->filePath;
    }

    /**
     * Set file
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
    }

    /**
     * Get file
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    public function getLocale() {
        return $this->locale;
    }

    public function setLocale($locale) {
        $this->locale = $locale;
        return $this;
    }

    function getAdBanners() {
        return $this->AdBanners;
    }

    function setAdBanners(AdBanners $AdBanners) {
        $this->AdBanners = $AdBanners;
    }

}

<?php

namespace Application\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="freemoni_addbanner_translation")
 *  
 * @ 
 */
class AdBannersTranslation implements \A2lix\I18nDoctrineBundle\Doctrine\Interfaces\OneLocaleInterface {

    use \A2lix\I18nDoctrineBundle\Doctrine\ORM\Util\Translation;

    /**
     * @var string
     *
     * @ORM\Column(name="bannerTitle", type="string", length=255)
     */
    private $bannerTitle;

    /**
     * @var string
     *
     * @ORM\Column(name="bannerLink", type="string", length=255)
     */
    private $bannerLink;

    /**
     * @ORM\OneToOne(targetEntity="FileLocalize", cascade={"persist"})
     * @ORM\JoinColumn(name="translatable_file_id", referencedColumnName="id")
     * @Assert\Valid()
     * @Assert\Type(type="Application\AdminBundle\Entity\FileLocalize")
     * */
    private $translatableFile;

    public function getId() {
        return $this->id;
    }

    function getBannerTitle() {
        return $this->bannerTitle;
    }

    function getBannerLink() {
        return $this->bannerLink;
    }

    function setBannerTitle($bannerTitle) {
        $this->bannerTitle = $bannerTitle;
    }

    function setBannerLink($bannerLink) {
        $this->bannerLink = $bannerLink;
    }

    function getFile() {
        return $this->file;
    }

    function setFile($file) {
        $this->file = $file;
    }

    /**
     * Set translatableFile
     *
     * @param $translatableFile
     */
    public function setTranslatableFile(FileLocalize $translatableFile = null) {
        $this->translatableFile = $translatableFile;
    }

    /**
     * Get translatableFile
     *
     * @return $translatableFile
     */
    public function getTranslatableFile() {
        return $this->translatableFile;
    }

}
and the controller action is
public function createAction(Request $request) {
        $entity = new AdBanners();

        $form = $this->createForm(new AdBannersType(), $entity);

        $files = $request->files->get('application_adminbundle_adbanners');
        $formArray = $request->request->get('application_adminbundle_adbanners');
        //print_r($formArray);

        foreach ($files['files'] as $k => $file) {
            // echo $file->getClientOriginalName();
            // echo $file['file'];
            $em = $this->getDoctrine()->getEntityManager();
            $fileimg = new FileLocalize();
            print_r($file);
            $entity->setFiles($file->$fileimg->getFile());
           // $fileimg->setFilePath($fileimg->getFile());
            $fileimg->setLocale('en');
         echo   $fileimg->getFile();
            // $documents = new ArrayCollection();
            //$documents->add(new FileLocalize());
            $repository2 = $em->getRepository('Gedmo\\Translatable\\Entity\\Translation');
            //echo $file['file'];
            $fileimg->setFile($file['file']);
            //$repository2->translate($fileimg, 'file', 'en', $file['en']);
            //$repository2->translate($fileimg, 'file', 'es', $file['es']);
            //$form->get('files')->setData(array('files' => $documents));
            //  $this->getRequest()->files['file']->getClientOriginalName();
            //$img->setAdBanners($entity);
            //$img->setFile();
            $em->persist($fileimg);
            $em->flush();

            // $someNewFilename = date('Y-m-d-H-i-s') . $files->getClientOriginalName();
            $dir = __DIR__ . '/../../../../web/';

            // $form['files'][$k]->getData()->move($dir . '/upload', $someNewFilename);
            echo "<pre>";
        }

        $entity = new AdBanners();

        $imgForm = $this->createForm(new AdBannersType(), $entity);
        $em = $this->getDoctrine()->getEntityManager();
        $em->persist($entity);
        $em->flush();

        die;
//var_dump($imgForm->getData());
        print_r($img->getFile());
        // var_dump($form->getData());
        // print_r($form->get('foo')->getData());
//die();
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            /* $img->setFile($entity->getFranchiseLogo());
              $img->setPath('logo');

              if ($img->upload())
              $entity->setFranchiseLogo($img->getWebPath());
             * 
             */
            $em->persist($entity);
            $em->flush();
            $this->get('session')->getFlashBag()->add('info', "Franchise Added Sucessfully");
            return $this->redirect($this->generateUrl('admin_adbanners'));
        }
        $this->get('session')->getFlashBag()->add('danger', "There are some errors in the submitted form!" . $form->getErrors());
        return array(
            'entity' => $entity,
            'form' => $form->createView(),
        );
    }

**Comment by giovkanata** [comment]
I suggest you to post this type of question on [StackOverflow](http://stackoverflow.com/).
PS: before to post, search if exist a similar question that already have a solution.
