### ISSUE TITLE
Deprecated option 'max_length' added to fields

### ISSUE THREAD

**Issue by MeiKuei** [a2lix/TranslationFormBundle#219]
Hi,
when an entity field has length parameter set, the function **guessMissingFieldOptions**  in **TranslationFormBundle/TranslationForm/TranslationForm.php** automatically add 'max_length' option in field which is deprecated in Symfony 3.
This make an exception is thrown during template rendering.

Thanks for your help

**Comment by nataliastanko** [comment]
Same problem here.

**Comment by webda2l** [comment]
Related to https://github.com/a2lix/TranslationFormBundle/pull/220

**Comment by webda2l** [comment]
New tag https://github.com/a2lix/TranslationFormBundle/releases/tag/2.1.1 created, update the bundle and try again.

**Comment by nataliastanko** [comment]
I used that fork yesterday, it worked :) It works with tag 2.1.1 here.

**Comment by webda2l** [comment]
Fine, I close. Thanks for feedback.
