### ISSUE TITLE
Translation on single field 

### ISSUE THREAD

**Issue by mred28** [a2lix/TranslationFormBundle#222]
Hi guys,
I have a question.

Normally when I build the form using the FormBuilderInterface Symfony, and I use `a2lix_translationsForms`.

In this case I've a dynamic form and using FormInterface on a Symfony Project.
Which of these `a2lix_translationsFields, a2lix_translations, a2lix_translationsForms, a2lix_translationsLocalesSelector, a2lix_translatedEntity` should I use to add the translation to a single field?

Thank you

**Comment by webda2l** [comment]
If translation is about entire entity: a2lix_translationsForms (and so it need locale field in entity)
If translation is about some fields: a2lix_translations (and so it need to choose a strategy, KnpDoctrineBehavior for the most recommended)
