### ISSUE TITLE
reorder translatable fields and add non translatable fields in betwean two translatable fields

### ISSUE THREAD

**Issue by sosojni** [a2lix/TranslationFormBundle#226]
Right now, i have this in my form builder:
$builder ->add('translations', 'a2lix_translations')->add('subject');

I get form:
descriotion (translateable)
title (translateable)
subject (not translateable)

How do i get:
title (translateable)
subject (not translateable)
description (translateable)

How can i reorder fields and insert not translateable field in betwean two translateable ones?

**Comment by WildChildForLife** [comment]
I have the same issue, has anyone found the solution ?

**Comment by sosojni** [comment]
I did. It is not mentioned in docs but you can do this:
In twig file where is your form add 

    {% import "A2lixTranslationFormBundle::macros.html.twig" as a2lixTranslations %}

and than add form and its fields in any order you want

    {{ form_errors(edit_form) }}
    {{ form_start(edit_form) }}
      {{ form_row(edit_form.nottranslateablefield1) }}    
      {{ a2lixTranslations.partialTranslations(edit_form.translations, ['translatablefield1']) }}
      {{ form_row(edit_form.nottranslateablefield2) }}
      {{ a2lixTranslations.partialTranslations(edit_form.translations, ['translatablefield2']) }}
      {{ form_row(edit_form.nottranslateablefield3) }}
      {{ a2lixTranslations.partialTranslations(edit_form.translations, ['translatablefield3']) }}
      {{ form_row(edit_form.nottranslateablefield4) }}
    {{ form_end(edit_form) }}

**Comment by webda2l** [comment]
Simple way is doing the right ordering in your entity

````
protected $title
protected $subject
protected $description
````

Otherwise, partialTranslations macro, yes..
