### ISSUE TITLE
Is there option to set translatable fields only for one locale + hide tabs?

### ISSUE THREAD

**Issue by andrzejdziekonski** [a2lix/TranslationFormBundle#227]
Hi, 

i would like to pass **one** locale parameter to my form and render form fields only for this locale in some unordinary case (and there would be no need for rendering tabs). Can i do it with this bundle or i need to manually set up translation CollectionType? I know i can pass locales array with one element to A2lixTranslationsType and then hide tabs with css but this looks like an workaround.

I am using KNP behaviours if it matters.

**Comment by andrzejdziekonski** [comment]
Ok i think i solved this one if whole form needs tabless fields. I defined two templates for a2lix widget one with tabs and second tabless and in my template i define which form_theme to use.

**Comment by webda2l** [comment]
Hi,

For each 'a2lix_translations' fields (or TranslationsType::class in symfony 3.x) you can override default locales to display as:

````
            ->add('translations', TranslationsType::class, [
                'locales' => ['en', 'de'],
            ])
````
