### ISSUE TITLE
How to order translate list ?

### ISSUE THREAD

**Issue by Hesiode** [a2lix/TranslationFormBundle#230]
By Example, this doesnt work : 

`            ->add('pays', EntityType::class, array(
                'class' => 'AppBundle:Referentiel\Pays',
                'preferred_choices' => array('France'),
                'property' => 'translations[' . $options["locale"] . '].nomPays',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('e')
                        ->select('e', 't')
                        ->join('e.translations', 't')
                        ->orderBy('t.nomPays', 'ASC');
                },
            ))`

**Comment by webda2l** [comment]
Example https://github.com/a2lix/Demo/commit/faefbc8f5bfe363a381301a618eb2a66c9a4ec45 work for me.
Maybe another problem on your side.
