### ISSUE TITLE
Translations not working?

### ISSUE THREAD

**Issue by cv21** [a2lix/TranslationFormBundle#237]
I use translations for sonata admin forms and I can't translate form generated by TranslationFormBundle.
[Screenshot](http://screencloud.net/v/nyp7)

**Comment by webda2l** [comment]
If you speak about label, as native symfony form, is up to you to set the right label, or key. http://symfony.com/doc/current/translation.html

So:

````
$builder->add('translations', 'a2lix_translations', [
    'fields' => [
        'description' => [
            'locale_options' => [
                'es' => ['label' => 'descripción'],         // or keyword     'es' => ['label' => 'form.description.es'], 
                'fr' => ['label' => 'description']        // or keyword      'fr' => ['label' => 'form.description.fr'], 
            ]
        ]
    ]
]);
````

With key usage, another solution is use your own template https://github.com/a2lix/TranslationFormBundle/blob/master/Resources/views/default.html.twig that could create a standardized keys.
