### ISSUE TITLE
Could not load type "a2lix_translations"

### ISSUE THREAD

**Issue by NovikovViktor** [a2lix/TranslationFormBundle#241]
Hello,
I am using Symfony 3.1.*  and I want to bind this bundle with SonataAdmin.
I have configured everything as it is described in  documentation, but get exception:
`Could not load type "a2lix_translations"`
I tried to research solution but didn't get any results. 
Is it compatible with 3.1 version?
Could somebody help me?

**Comment by webda2l** [comment]
Hello,

I need to update documentation.
With Symfony 3.0+, you need to explicit the class name of the desired type.

So 

````
$builder->add('translations', \A2lix\TranslationFormBundle\Form\Type\TranslationsType)
````

or

````
use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
...
$builder->add('translations', TranslationsType::class)
````

See https://github.com/a2lix/Demo/blob/master/src/A2lix/DemoTranslationA2lixBundle/Form/ProductType.php#L18

**Comment by NovikovViktor** [comment]
Thanks @webda2l , works as expected now. 
>I need to update documentation.
It would be great.

Best regards, Viktor

**Comment by webda2l** [comment]
You're welcome.

Documentation updated http://192.168.1.20:4000/bundles/translation-form/2.x.html#bundle-usage, I close this issue.
