### ISSUE TITLE
Elastic search + A2lix + JMS Serializer = Parameter 'locale' does not exist.

### ISSUE THREAD

**Issue by starmate** [a2lix/TranslationFormBundle#250]
Hi,

It seems that there is a problem when using elastic search command (php app/console fos:elastica:populate), only with JMS Serializer active.

It says [InvalidArgumentException] Parameter 'locale' does not exist. 

ps: when I sent oneLocale: enabled: false it works

Any clue about this?

Thanks,

Jon

**Comment by jordisala1991** [comment]
Without further information, hard to help. Closing.
