### ISSUE TITLE
Version 2.x : add support for symfony 3.1

### ISSUE THREAD

**Issue by Mondane** [a2lix/TranslationFormBundle#251]
I've this construction:

```php
// $formBuilder = \Symfony\Component\Form\FormBuilder
                $formBuilder
                    ->add('translations', TranslationsType::class, array(
                            'exclude_fields' => array(

                            ),
                            'fields' => array( // Explicitly set labels for a2lix_translations
                                'title' => array(
                                    'label' => 'input.title',
                                ),
                                'introduction' => array(
                                    'label' => 'input.introduction',
                                ),
                                'contents' => array(
                                    'label' => 'input.contents',
                                ),
                            ),
                        )
                    );
```
Which worked fine in symfony 2.8, but after upgrading to 3.1, I get these errors:

>The options "exclude_fields", "fields" do not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "mapped", "method", "post_max_size_message", "property_path", "required", "translation_domain", "trim", "upload_max_size_message", "validation_groups".

After I remove those non-existing options, my site loads a bit further, but now I get these errors:

>Notice: Undefined index: fields

Might have to do with:

>You have to use configureOptions() from OptionsResolver instead of setDefaultOptions() from OptionsResolverInterface

**Comment by Mondane** [comment]
Well, it turns out this bundle already has support for symfony 3.x but the installation instructions make it so only versions 2.0.0 up to 2.1.0 are installed. The support has been added in 2.1.0 and up.

Change in your *composer.json*

`"a2lix/translation-form-bundle": "~2.0.0",`

to 

`"a2lix/translation-form-bundle": "^2.1",`

**Comment by enrike1983** [comment]
actually I'm still facing this issue even changin the bundle version
