### ISSUE TITLE
Unable to find the association target class of "equipment__translations" in EntityBundle\Entity\Etablissement\EquipmentLightVersion.

### ISSUE THREAD

**Issue by starmate** [a2lix/TranslationFormBundle#252]
Hi Everyone,

I am using A2lix Translatable within sonata and it works perfectly. However, when I try access translatable of OneToOne related entity, I have the following error message:

> Unable to find the association target class of "equipment__translations" in EntityBundle\Entity\Etablissement\EquipmentLightVersion.

Here is the code used within sonata admin class:
`->add('equipment.translations', TranslationsType::class)`

And here is the join (from EntityBundle\Entity\Equipment\EquipmentLightVersion entity):
```
/**
     * @ORM\OneToOne(targetEntity="EntityBundle\Entity\Equipment\Equipment")
     * @ORM\JoinColumn(nullable=false)
     */
    private $equipment;
```

I am not sure if this is a bug or misusage.

Any clues on how to fix this?

Thanks in advance,

Jon

**Comment by jordisala1991** [comment]
I don't think this issue belong here, since SonataAdmin handles forms in a tricky way.

Please, if you still have this issue, maybe try posting it to Sonata, where we can help if it is really a bug on our end, or post it to stackoverflow (as Sonata recommends for questions).

Closing.

**Comment by kakhavk** [comment]
I have same issue where I don't have SonataAdmin installed,  but is only symfony. after upgrade from symfony 3 to 4 this error appears.
`REQUES Uncaught PHP Exception RuntimeException: "Unable to find the association target class of "translations" in AppBundle\Entity\User." at /home/.../vendor/a2lix/auto-form-bundle/src/ObjectInfo/DoctrineORMInfo.php line 54`

**Comment by bobalazek** [comment]
I'm having the same issue but in EasyAdmin. Did anyone found a solution for that?
