### ISSUE TITLE
Could I use atlantic18n DoctrineExtension with a2lix?

### ISSUE THREAD

**Issue by asgardia7** [a2lix/TranslationFormBundle#253]
Hello,

I used to use atlantic18n DoctrineExtension (stof in symfony) with gedmo with a2lixTranslationFormBundle. I got error missing entityTranslation class now. At least could I use it without Personal Translations but only Entity Translation?
Any you, the best case is I could use it without separate Entity Translation for each entity.

Thanks please :)

**Comment by jordisala1991** [comment]
This is duplicate of, https://github.com/a2lix/TranslationFormBundle/issues/187

Closing
