### ISSUE TITLE
Customize template

### ISSUE THREAD

**Issue by kironet** [a2lix/TranslationFormBundle#257]
Hey,
can someone help me. How can I modify default template to bootstrap version? Because input's doesn't have a class "form-control".

I have no idea what should I insert/delete/modify in default template :(

 Thanks

**Comment by V34s** [comment]
Did you configure Symfony to use Bootstrap form-templates?
http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme

**Comment by jordisala1991** [comment]
As @V34s pointed out, you can change the form render as you want. It is a Symfony feature, that we don't override in any way.

Also, if you need to change the main template for the formType, you could probably do it, by extending our template. This is a Symfony feature too: https://symfony.com/doc/current/templating/overriding.html

Closing. If you feel this is an issue still, please ping me to reopen with more information.
