### ISSUE TITLE
How to manage multidimensional array name of fields at server side validation with this extension?

### ISSUE THREAD

**Issue by nikunjkabariya** [a2lix/TranslationFormBundle#258]
Hello,
I am having two tables content_pages and content_page_translations.
When I build the form, form field name generated is like this:   
content_page[translations][en][pageTitle]
Now, let me know How to manage multidimensional array server side validation with this extension?

Thanks

**Comment by jordisala1991** [comment]
You can add Symfony constraints to any field inside the translations, just like you would do with a field the form, with the attribute 'constraints'. Or you can add the asserts on the `ContentPageTranslation` that you have.

Docs should provide you more information about this: http://a2lix.fr/bundles/translation-form/3.x.html#bundle-usage

Closing.

If you feel this is still an issue, please ping me to reopen and provide more information to help you.
