### ISSUE TITLE
using translationType with a EntityType field

### ISSUE THREAD

**Issue by skytorner** [a2lix/TranslationFormBundle#259]
Hi ! 
I got this a Bonus entity which contains translated differents fields.
I want one of these fields (promotion) to be a select input coming from Promotion entity.

So according to a2lix documentation, I did this : 

//other uses...
 use Symfony\Bridge\Doctrine\Form\Type\EntityType;
 use A2lix\TranslationFormBundle\Form\Type\TranslationsType;

public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('tag', TextType::class)
        ->add('translations', TranslationsType::class, [
            'fields' => [
                'promotion' => ['field_type' => EntityType::class, [
                    'class' => 'AdminBundle:Promotion',
                    'choice_label' => 'getName'
                ] ]
            ]
        ])
        ->add('Save', SubmitType::class)
    ;
}

but i go to the Add page, i got this error : 

The option "0" does not exist. Known options are: "action", "attr", "auto_initialize", "block_name", "by_reference", "compound", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "inherit_data", "intention", "label", "label_attr", "label_format", "mapped", "max_length", "method", "pattern", "post_max_size_message", "property_path", "read_only", "required", "translation_domain", "trim", "virtual"

Can you explain what imma doing wrong ?

thks

**Comment by jordisala1991** [comment]
It took me some time to understand this issue, next time, please, consider using the github features to post code in a better way, because it is hard to read that code.

You are having the same issue as this other guy: https://github.com/a2lix/TranslationFormBundle/issues/261

Good news is that it can be solved in the same way. Problem is you are trying to add an array for the field type options, when you have to put them at the same level. Look at the issue linked and also at the docs of this bundle: http://a2lix.fr/bundles/translation-form/2.x.html

Closing. If you feel this should remain opened for some reason, ping me.

**Comment by skytorner** [comment]
I reopen this cause I got kinda  same problem : 
Everything was working fine (and with @jordisala1991's hint) in SF2.8 (with A2lix/translations-form 2.1)

Im doing this new project and I took this opportunity to learn SF4. 
Obviously A2lix's bundle has been updated too. 

Now, when i'im using a entityType in my form, I have SF saying the field doesnt exist in the translation Entity...
In this case it's the WRITER field that doesnt exist in ArticleTranslation.

Article Entity 
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
 
class Article
{
     use ORMBehaviors\Translatable\Translatable,
            ORMBehaviors\Timestampable\Timestampable
     ;
     //....
}
```

ArticleTranslation  Entity
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

class ArticleTranslation
{
       use ORMBehaviors\Translatable\Translation;
  
       /**
        * @ORM\ManyToOne(targetEntity="App\Entity\Writer")
        * @ORM\JoinColumn(nullable=true)
        */
       private $writer;

       //getter + setter ...
}
```

Writer Entity
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;

class Writer
{
     private $name
     //getter + setter
}
```

ArticleType
```php
namespace App\Form;
//...other use 'optionsResolver, etc..
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Writer;

use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
use A2lix\TranslationFormBundle\Form\Type\TranslatedEntityType; //thought 'bout using this type but ... I dont know what is it for

 public function buildForm(FormBuilderInterface $builder, array $options)
{
        $builder
            ->add('translations', TranslationsType::class, [
                'fields' => [
                    'slug'            => ['field_type' => TextType::class],
                    'title'           => ['field_type' => TextType::class],
                    'content'         => ['field_type' => CKEditorType::class],
                    'redacteur'     => [
                        'field_type'   => EntityType::class,
                        'class'        => Writer::class,
                        'choice_label' => function ($writer) {
                            return $writer->getName();
                        }
                    ]
                ],  
            ])
        ;
}
```
