### ISSUE TITLE
Problems with Lexik\Bundle\TranslationBundle

### ISSUE THREAD

**Issue by BigBazooka007** [a2lix/TranslationFormBundle#260]
Hi. When i install a2lix and Lexik\Bundle\TranslationBundle i have errors. 
"The target-entity Lexik\Bundle\TranslationBundle\Model\TransUnitTranslation cannot be found in 'Lexik\Bundle\TranslationBundle\Model\TransUnit#translations'."

The problem occurs because a2lix/i18n-doctrine-bundle is injecting its own mapping information.
Is there any way to make itd compatible?

**Comment by faizanahmad** [comment]
Having same issue. Did you find any workaround? @BigBazooka007

**Comment by tchapi** [comment]
Hi all

Is this still the case ?
