### ISSUE TITLE
ChoiceType in translation not working

### ISSUE THREAD

**Issue by Renjyy** [a2lix/TranslationFormBundle#261]
Hello 

I dont know if im not using it well but when I want to put a ChoiceType in a translation, I got this error :

The option "0" does not exist. Defined options are: "action", "allow_extra_fields", "attr" .......

Here's my form :

      ->add('translations', TranslationsType::class, [
                   'fields' => [
                       'typesGame' => [
                           'field_type' => ChoiceType::class, [
                               'choices' => [
                                  'entry1' => 'option1',
                                  'entry2' => 'option2',
                                  'entry3' => 'option3',
                              ]
                          ]
                      ]
                  ]
              ])

Is this the proper way to use ChoiceType with the bundle or am i doing it wrong ?

**Comment by jordisala1991** [comment]
Your field definition is wrong, it should be (as docs say http://a2lix.fr/bundles/translation-form/2.x.html):

**Comment by jordisala1991** [comment]
Closing
