### ISSUE TITLE
Tab Label Value

### ISSUE THREAD

**Issue by jayesbe** [a2lix/TranslationFormBundle#262]
Tried searching but couldn't find an answer.

I have 3 languages EN, FR, and ES.

The tabs show as En, Fr, Es

How do I make the tabs show, English French Spanish ?

**Comment by rachidbigm** [comment]
Hi,

For a simple dirty solution :
- You can try overriding the a2lix form template and inside that twig file you can test on languages code and display the complete name of the language as you like.

Else for a good fix: 

- Override TranslationsType "configureOptions" method and then add your custom option in the resolver
- Override the twig template and then do a dynamic test between passed languages code and your custom passed, lets say array with your locales as key and complete name as content.

**Comment by jordisala1991** [comment]
It could be probably be an issue on the documentation. But looking at the template, seems like there is something to change the tab label: 

https://github.com/a2lix/TranslationFormBundle/blob/master/Resources/views/default.html.twig#L10

I leave this open in case we update the docs, to reflect this feature.
