### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by mssimi** [a2lix/TranslationFormBundle#264]
Hey

in documentation there is option excluded_fields, which should be exclude_fields.

**Comment by jordisala1991** [comment]
https://github.com/a2lix/TranslationFormBundle/blob/8680c6a11d37de91d4081910bd3b87ae4848bb7d/Form/Type/TranslationsType.php#L75

The code says it is "excluded_fields". So there is no mistake in docs.
Closing. Feel free to ping me to reopen if this is still relevant.

**Comment by jordisala1991** [comment]
There is indeed a mistake on the 2.x branch https://github.com/a2lix/TranslationFormBundle/blob/2.x/Form/Type/TranslationsType.php#L72

it is `exclude_fields`. Reopening
