### ISSUE TITLE
Sonata a2lix 

### ISSUE THREAD

**Issue by maavia10** [a2lix/TranslationFormBundle#265]
Now i am Facing this Error while saving data to database 
Call to a member function set() on null
 vendor/a2lix/i18n-doctrine-bundle/A2lix/I18nDoctrineBundle/Doctrine/ORM/Util/Translatable.php (line 25) 
please help me asap

**Comment by jordisala1991** [comment]
Without an stack trace, and the concrete problem you have, hard to help. Closing
