### ISSUE TITLE
Text Direction change

### ISSUE THREAD

**Issue by maavia10** [a2lix/TranslationFormBundle#268]
Hi i am seeking any help regarding changing direction of text from right to left for arabic input in sonata admin for specific locale. please guide me how i can acheive this my configuration are well and working fine with A2lixI18nDoctrineBundle An indexBy strategy this strategy

**Comment by jordisala1991** [comment]
http://a2lix.fr/bundles/translation-form/2.x.html

As the docs suggest, you can probably add some additional classes or attributes to certain inputs under certain languages. So this should be doable without having to implement additional features.

Closing.
