### ISSUE TITLE
Error on translating arrays

### ISSUE THREAD

**Issue by tiagojsag** [a2lix/TranslationFormBundle#27]
Hi,

First of all, I'm not sure if this is a bug on your part, so I apologize in advance if it isn't. I'm just hoping you can help me out:

I created a custom form field type called "choice plus other" that, just like the name suggests, has a choice field, with a bunch of options including an "other" which, if selected, displays a text input. This is mapped to an entity field type array. I had to struggle a bit to get it working (for some reason, symfony didn't initialize an array for the field, but a string, which then made doctrine really sad), but now it's done. Next stop, translating it in SonataAdmin.

Here's the real problem: I added the "translatable" annotation to the field, and started getting errors when saving my entity with SonataAdmin, about an array to string conversion. Turns out that the array that comes from the translations section for this field is not being serialized prior to being commited, ence the error. I solved it for now by creating another field type and adding a transformer that serializes it, but I think it would be nice if this could be done automatically.

Like I said, I'm not sure this is a problem with this bundle, so if it isn't, please just point me in the right direction and I'll go knock on somebody else's door.

Thanks for sharing this bundle with the community, it's really useful

cheers

**Comment by aistis-** [comment]
This feature would be an useful addon :)

**Comment by jordisala1991** [comment]
I don't really understand how this is a bug / feature for this bundle. Unless you provide more information about this, we can't really fix anything. 

¿Is this array formType working outside the translationType?

Closing since this is 4 years old but if we find out more information and it is a problem on our side, we can reopen.
