### ISSUE TITLE
Buildform - certain number of fields

### ISSUE THREAD

**Issue by bepabg** [a2lix/TranslationFormBundle#275]
I’ve built a form with translations and want to show a certain number of fields, not everything from database. I added only 2 fields in buildForm class, but at twig form render there display me all the fields from translation entity. 
Can you please tell me how to display fields only from builForm class?

**Comment by bepabg** [comment]
Here is my buildForm
![buildform](https://user-images.githubusercontent.com/14800822/33660357-3276134e-da8c-11e7-98be-167a5bfcd0d5.jpg)

Twig render
![twig](https://user-images.githubusercontent.com/14800822/33660359-3291e56a-da8c-11e7-9909-ced3650cba7b.jpg)

and View in browser, Why the is last 3 fields? and how to remove them? I know that may hide them with css, but that's not the right way
![view](https://user-images.githubusercontent.com/14800822/33660362-32ab5b12-da8c-11e7-8bbb-f6911ca9ef4a.jpg)

**Comment by webda2l** [comment]
Theses fields are in your TranslationEntity, maybe from a trait or..? Your database must be have theses fields as well.

Use 'excluded_fields' option to avoid their display. See http://a2lix.fr/bundles/translation-form/2.x.html#bundle-configuration

**Comment by bepabg** [comment]
> 10x webda2l
'excluded_fields' is my solution

**Comment by webda2l** [comment]
Fine. I close the issue
