### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by bocharsky-bw** [a2lix/TranslationFormBundle#277]
Any plans to support Symfony 4?

**Comment by jgrygierek** [comment]
That would be great. I don't see any bundles with similar functionality, so if this bundle won't have a SF4 support, we have problem...

**Comment by jordscream** [comment]
any update ?

**Comment by Akyna** [comment]
Very useful bundle.
It will be bad if in symfony 4 it will not be..

**Comment by Soullivaneuh** [comment]
A PR was opened (https://github.com/a2lix/TranslationFormBundle/pull/280) but without any answer.

If someone want to make an another one, I'll be glad to review it.

A fix on the 2.x stable branch can be done IMHO.

**Comment by welcoMattic** [comment]
Is it possible to release a 2.x version as soon as possible with Symfony 4 support?

**Comment by jordisala1991** [comment]
I would like this to be fixed before releasing: https://github.com/a2lix/TranslationFormBundle/pull/289
