### ISSUE TITLE
Bundle maintenance

### ISSUE THREAD

**Issue by jordisala1991** [a2lix/TranslationFormBundle#278]
Hello,

is anyone maintaining this bundle? There are some things I would like to fix on the bundle but I am not sure wether to fork and fix them on my own or if I can do PRs here and will get merge.

cc/ @webda2l 

Thank you for your time :)

**Comment by jgrygierek** [comment]
Better do it on your own.

BTW, last commit was ~1.5 year ago. So I think it is time to find someone to manage this bundle.

**Comment by Soullivaneuh** [comment]
The branch is for 3.x and no release was done. But some work is already done.

@webda2l May you delegate some rights to others in order to keep maintaining?

**Comment by jordisala1991** [comment]
In the meantime I will start mantaining our own fork. This bundle is so useful to dissapear

**Comment by webda2l** [comment]
Hello,

Quite busy elsewhere and with with some motivation gone, yes this bundle has very low activity for now.. :/

I've seen https://github.com/uerka/TranslationFormBundle earlier this month, which have done some planned work, maybe you could give a try.

I will try to re-motivate myself before the end of the week to make planned progress.
Otherwise, yes a possibility will be to add collaborator(s) in a first time and transfer ownership in a second time if I completely give up.

**Comment by jordisala1991** [comment]
@webda2l your last message was 22 days ago. Did you make some progress on this?

Are you willing to add some collaborators?

**Comment by Soullivaneuh** [comment]
> I've seen https://github.com/uerka/TranslationFormBundle earlier this month, which have done some planned work, maybe you could give a try.

Only Knp behavior is supported on this bundle.

@webda2l I would like to maintain at least the current 2.x stable branch. Some important fix PRs are needed such as #282 and #283.

Can you please consider give to @jordisala1991 and I some push right? Thanks!

**Comment by webda2l** [comment]
Ok because I always not sure about when I'll really have time to this project, I sent invitation to add both of you as collaborator.

**Comment by Soullivaneuh** [comment]
Thanks @webda2l!

About 3.x it seems it required auto-form: https://github.com/a2lix/TranslationFormBundle/blob/master/UPGRADE-3.0.md#bc-break-new-a2lixautoformbundlea2lixautoformbundle-is-required-as-additional-bundle-in-your-appkernel

It would be great to have push right to this bundle too if you want us to participate to the next major.

**Comment by Soullivaneuh** [comment]
@webda2l Also, I don't have any right on the repo, I'm just part of the organization.

According to @jordisala1991, I'm not on the right team.

**Comment by webda2l** [comment]
@Soullivaneuh you're welcome! Added!

**Comment by jordisala1991** [comment]
This can be closed
