### ISSUE TITLE
bundle compatible

### ISSUE THREAD

**Issue by salimmejdoub** [a2lix/TranslationFormBundle#279]
Hello 
is this bundle compatible with symfony 3.4
i tried to run but 
it return me cant find default.html.twig
thanks

**Comment by LanmanGroup** [comment]
Yes, you also need to enable the templating component in your config:
```
framework:
    templating:
        engines: ['twig']
```

I think this it's all...

**Comment by salimmejdoub** [comment]
Thank a lot 
you saved my life
