### ISSUE TITLE
Html validator not switch tab

### ISSUE THREAD

**Issue by Losams** [a2lix/TranslationFormBundle#281]
Hi, 

When in my form I place a "required" field (let's say for exemple "title"), a html attribut is on my field DOM (it's ok). If I go on one lang tab, i fill "title en", and submit, a HTML validator will trigger (the translation "title es" is empty) but nothing will be display because there is no tab switch to show the concern input. It seems to do nothing for the user.

Have you some sort of solution for that ?

**Comment by jordisala1991** [comment]
Those 2 PR are related to your issue: #271 #249 

Feel free to help those guys (read all the comments there) with the testing of the PRs

**Comment by jorenvh1** [comment]
@jordisala1991 When will these be merged?

**Comment by webda2l** [comment]
@jorenvh1 New tagged version. Update this project.
