### ISSUE TITLE
using EntityType within TranslationType field

### ISSUE THREAD

**Issue by skytorner** [a2lix/TranslationFormBundle#310]
I reopen this cause I got kinda  same problem : 
Everything was working fine (and with @jordisala1991's hint) in SF2.8 (with A2lix/translations-form 2.1)

Im doing this new project and I took this opportunity to learn SF4. 
Obviously A2lix's bundle has been updated too. 

Now, when i'im using a entityType in my form, I have SF saying the field doesnt exist in the translation Entity...
In this case it's the WRITER field that doesnt exist in **_ArticleTranslation_**.

nb : What I want to do is to be able to set a different WRITER for each translation

Article Entity 
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
 
class Article
{
     use ORMBehaviors\Translatable\Translatable,
            ORMBehaviors\Timestampable\Timestampable
     ;
     //....
}
```

ArticleTranslation  Entity
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

class ArticleTranslation
{
       use ORMBehaviors\Translatable\Translation;
  
       /**
        * @ORM\ManyToOne(targetEntity="App\Entity\Writer")
        * @ORM\JoinColumn(nullable=true)
        */
       private $writer;

       //getter + setter ...
}
```

Writer Entity
```php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;

class Writer
{
     private $name
     //getter + setter
}
```

ArticleType
```php
namespace App\Form;
//...other use 'optionsResolver, etc..
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Writer;

use A2lix\TranslationFormBundle\Form\Type\TranslationsType;
use A2lix\TranslationFormBundle\Form\Type\TranslatedEntityType; //thought 'bout using this type but ... I dont know what is it for

 public function buildForm(FormBuilderInterface $builder, array $options)
{
        $builder
            ->add('translations', TranslationsType::class, [
                'fields' => [
                    'slug'            => ['field_type' => TextType::class],
                    'title'           => ['field_type' => TextType::class],
                    'content'         => ['field_type' => CKEditorType::class],
                    'redacteur'     => [
                        'field_type'   => EntityType::class,
                        'class'        => Writer::class,
                        'choice_label' => function ($writer) {
                            return $writer->getName();
                        }
                    ]
                ],  
            ])
        ;
}
```

This post is a follow-up of [259](https://github.com/a2lix/TranslationFormBundle/issues/259) but the issue was closed so I reopened it 

Thanks , and sorry in advance it I should put it in [259](https://github.com/a2lix/TranslationFormBundle/issues/259)

**Comment by webda2l** [comment]
Translate only some fields of an entity: Translation concept with KnpLabs or other strategy.
Fully different entity by locale: Another concept that I name Localized. See https://github.com/a2lix/Demo/blob/master/app/src/Entity/CompanyMediaLocalize.php for an example.

You say want "set a different WRITER for each translation", so you could do similar to Company-CompanyMediaLocalize example of the Demo.
