### ISSUE TITLE
Error installing the bundle: non-existent service "a2lix_auto_form.manipulator.default"

### ISSUE THREAD

**Issue by arirangz** [a2lix/TranslationFormBundle#312]
#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.

symfony/monolog-bundle     v2.12.1 v3.3.0 Symfony MonologBundle
symfony/polyfill-apcu      v1.8.0  v1.8.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.8.0  v1.8.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.8.0  v1.8.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.8.0  v1.8.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.8.0  v1.8.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.8.0  v1.8.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.8.0  v1.8.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.12 v4.1.1 The Symfony PHP framework

#### PHP version

```
$ php -v
# Put the result here.
PHP 7.2.7 (cli) (built: Jun 19 2018 23:14:45) 

## Subject

On symfony 3.4 I'm trying to install TranslationFormBundle and I'm getting an error

## Steps to reproduce
Adding 
 "a2lix/translation-form-bundle" : "dev-master",

And running:
php -d memory_limit=-1 Composer.phar update symfony/symfony --with-dependencies

## Expected results
Installing the bundle

## Actual results
The service "a2lix_translation_form.form.type.translations_type" has a dependency on a non-existent service "a2lix_auto_form.manipulator.default".

I checked and I can see nowhere this service. I even check on github in the master branch and nothing about this service. Could you please help me solving this issue?

Thanks!

**Comment by webda2l** [comment]
"a2lix_auto_form.manipulator.default" is part of the AutoFormBundle that is a dependency of the TranslationFormBundle.

Update symfony is a thing, and so, ```php -d memory_limit=-1 Composer.phar update symfony/symfony --with-dependencies``` is ok.
But installing new bundle is recommended with ```php -d memory_limit=-1 Composer.phar require a2lix/translation-form-bundle```.

**Comment by Dowdow** [comment]
I have the same error. I'm on Symfony 3.4 and I just upgraded from 2.x to 3.x on this bundle.
The problem comes from here:
https://github.com/a2lix/TranslationFormBundle/blob/dcf0716d8d0103c5389e48fe4a8787274e004728/src/Resources/config/a2lix_form.xml#L15

**Comment by koddistortion** [comment]
I know this comes quite late, but in your AppKernel make sure to register
`A2lix\AutoFormBundle\A2lixAutoFormBundle`
before registering 
`A2lix\TranslationFormBundle\A2lixTranslationFormBundle`
