### ISSUE TITLE
Get all translated fields in configureShowField()

### ISSUE THREAD

**Issue by artyuum** [a2lix/TranslationFormBundle#314]
Hi, first of all, I'm sorry if this issue is not related to _a2lix/TranslationFormBundle_.

I have 4 Entities : (please tell me if you wanna see them, I didn't put them on purpose because it would make the issue really long.)

1. **Posts**
2. **PostsTranslation**
3. **Categories**
4. **CategoriesTranslation**

A post can be assigned to several categories (ManyToMany) and all Posts (title and content fields) and Categories (name field) are translatable.

Here is the problem...
In **Sonata Admin**, when I want to **show a post** (which calls `configureShowFields()` method), I want to be able to see all translated fields for this post (title and content) in all languages.
For the **Posts** entity, only the following fields are translatable : 
- **title**
- **content**

Here is what I tried : 
```php
// BlogPostAdmin.php

$showMapper
->with('blog.languages')
    ->add('translations',
        NULL,
        [
            'label' => 'blog.translations'
        ]
    )
->end();
```
But, I get the following error : 
> You must define an `associated_property` option or create a `MyApp\WebsiteBundle\Entity\Blog\PostsTranslation::__toString`

If I add `'associated_property' => 'content'`, it obviously returns the content in all languages only and not the title.
And if I add the magic method `__toString()` it would be the same as adding `associated_property` as it would either return the content **OR** the title. Unless there is a way to return both ?

The ideal solution would be the following : 
```php
// BlogPostAdmin.php

$showMapper
->with('blog.titles')
    ->add('translations',
        NULL,
        [
            'associated_property' => 'title'
        ]
    )
->end()
->with('blog.contents')
    ->add('translations',
        NULL,
        [
            'associated_property' => 'content'
        ]
    )
->end();
```
But obviously, this would return the following error message : 

> Duplicate field name "translations" in show mapper. Names should be unique.

Any idea on how I can achieve that ?

Thanks in advance.

**Comment by webda2l** [comment]
Hi,

I have not used SonotaAdmin since a long time ago. For a easy CRUD admin, I'll tend to choose https://github.com/EasyCorp/EasyAdminBundle, which came later than Sonata.

That being said, I advice you to search on Github if you find similar case to yours: https://github.com/search?l=PHP&q=sonata+showmapper+translations&type=Code

Or otherwise fork https://github.com/a2lix/Demo and add a Sonata Admin case which allow me to easily reproduce your problem and see what can I suggest you.

**Comment by artyuum** [comment]
Alright, this is not an issue with your bundle then. Closing the issue.
Thanks.

**Comment by artyuum** [comment]
I ended up doing concatenation on the `__toString()` method. Something like : 
```php
public function __toString()
{
    $locale = '(' . $this->getLocale() . ') ';
    $title = $this->getTitle() . ' ';
    $content = $this->getContent();
    return (string) $locale . $title . $content;
}
```
A really dirty solution but I couldn't find a better way of showing all translated fields in the show action.
