### ISSUE TITLE
Empty translations are persisted after editing an entity

### ISSUE THREAD

**Issue by dachinat** [a2lix/TranslationFormBundle#320]
I should not add `NotBlank` assertion, because in my case translation is required to be supplied only for one locale (There is no required locale with a2lix configuration). 

Suppose I have entity A and I have created a record with translation `en` and empty for `fr`
Then I edited it: all empty values for `en` and new translation for `fr`

If I look to db, `en` translations are not removed, instead they're having `NULL` values.

Is there a way to remove translations from tables which are having `NULL` values? Similar to what `allow_delete` does with collections.

**Comment by Phenix789** [comment]
@dachinat Hi,

I had the same problem.
It come from `TranslationListener::submit()`
The method check if the entity is `empty()`.
Or, the entity is not empty (id, locale, ...).
* For [knp translatable](https://github.com/KnpLabs/DoctrineBehaviors#translatable), it should use `$entity->isEmpty()`.
* For [Gedmo](https://github.com/Atlantic18/DoctrineExtensions/tree/v2.4.x/lib/Gedmo/Translatable), I don't know.

```php
//TranslationListener.php
    public function submit(FormEvent $event): void
    {
        $data = $event->getData();

        foreach ($data as $locale => $translation) {
            // Remove useless Translation object
            if (empty($translation)) {
                $data->removeElement($translation);
                continue;
            }

            $translation->setLocale($locale);
        }
    }
```

---

To fix that quickly, you have several posibilities :

* In Sonata Admin project
Create a simple admin extension
```php
class TranslatableAdminExtension extends AbstractAdminExtension
{
    public function preUpdate(AdminInterface $admin, $object)
    {
        //Remove empty translation
        foreach ($object->getTranslations() as $translation) {
            if ($translation->isEmpty()) {
                $object->removeTranslation($translation);
            }
        }

        $object->mergeNewTranslations();
    }
}
```

* With Doctrine `LifeCycleCallback`
Not tested, but should be basically the same code. You can use a `trait`.

---

I will try to make a PR to fix that.

**Comment by dachinat** [comment]
@Phenix789 Thanks for taking a time to answer. I'm using KNP and I'll try with Doctrine LifeCycleCallback as soon as I'll have a chance.
