### ISSUE TITLE
Specify gedmo support in readme

### ISSUE THREAD

**Issue by sebsastianek** [a2lix/TranslationFormBundle#324]
Since there is no plan for latest (2.4) Gedmo support, please specify your readme 2.x section with supported versions.
Thanks!

**Comment by davidromani** [comment]
@sebsastianek it is possible to use `a2lix/translation-form-bundle` v2.4.2 version with Gedmo strategy `gedmo/doctrine-extensions` v2.4.36 ?

Thanks for your time ;-)

**Comment by ricardl** [comment]
Please, specify the support for Gedmo

**Comment by sebsastianek** [comment]
> @sebsastianek it is possible to use `a2lix/translation-form-bundle` v2.4.2 with Gedmo strategy `gedmo/doctrine-extensions` 2.4.36 version?
> 
> Thanks for your time ;-)

Hi @davidromani , i ended up writing my own form type :(

**Comment by iluuu1994** [comment]
@webda2l Can you please elaborate?

Following the docs results in this:

![image](https://user-images.githubusercontent.com/1752683/52557327-60719180-2def-11e9-8f99-f781dce55431.png)

This is definitely not the desired result, as it just lists the properties of the `Translation` entity.

**Comment by davidromani** [comment]
> Hi @davidromani , i ended up writing my own form type :(

@sebastianek can you provide me an example source code, please?

**Comment by jorenvh1** [comment]
I'm also interested in a way to use the 2.4 version with gedmo. @sebsastianek
