### ISSUE TITLE
Field(s) 'tagsText' doesn't exist

### ISSUE THREAD

**Issue by bepabg** [a2lix/TranslationFormBundle#348]
I'm using TranslationFormBundle with  Symfony 5.0.7,  BeelabTagBundle, Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface, Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait
My project is here -> [https://github.com/bepabg/Blog](https://github.com/bepabg/Blog)

If you build it, create database and run localhost/blog/new you will see the error:
Field(s) 'tagsText' doesn't exist in App\Entity\BlogTranslation
If I set tagsText in Blog entity everything is OK, but I want it to be in BlogTranslation entity.
When I call all translations - without one by one in FormType don't render tagsText field in view mode, if I call one by one, as in my project - there is errror, what's happend and why I received that error?

**Comment by tchapi** [comment]
Hi @bepabg 

If this issue is still valid, we need more info (code, minimal reproducible example if possible). From what I can see in your code `$tagsText` is not a mapped field, so I don't see how you can have it translated via Knp.

Thanks
