### ISSUE TITLE
Allow Symfony 6.0

### ISSUE THREAD

**Issue by jgrygierek** [a2lix/TranslationFormBundle#362]
Symfony 6.0 has been released so it would be good to allow it.

**Comment by tchapi** [comment]
Hi @jgrygierek 

Would you mind testing the https://github.com/a2lix/TranslationFormBundle/tree/dependencies/allow-symfony-6 branch just to be sure that we don't need anything more than the bump in the `composer.json` file ?

Thanks a lot 🙏🏼  !
