### ISSUE TITLE
[Question] How can we help ?

### ISSUE THREAD

**Issue by tchapi** [a2lix/TranslationFormBundle#363]
Hi @webda2l 

Not an issue _per se_, but I think this bundle is very interesting since it allows translated fields in EasyAdmin, which is a big plus for all the developers out there using EA in production (including myself). It seems to be the only sensible solution that exists, to be honest. So, great work, thanks a lot !

However, there does not seem to be much activity recently on your repo — maintaining OS software is hard, time-consuming and not always rewarding, so my question is: how can we help ?

Would you consider help with PRs / bug triage / so we can maybe update this repository to Sf5 / Sf6 and fix current bugs ?
Would you rather put a sponsor link somewhere, if you want to work on it on your own ?
Anything else we could do ?

Best !
Merci beaucoup
Cyril (🇫🇷)

**Comment by webda2l** [comment]
Hello Cyril,

Oui le temps me fait defaut, et sans être utilisateurs de mes bundles, je suis moins assidus à les maintenir correctement.
Je vous ajoute en collaborateur dans un premier temps si vous voulez faire du clair dans les issues & PRs, et valider le bon fonctionnement de SF6 avec une nouvelle release.
Et si par la suite, vous avez des ambitions de changements/améliorations de codes plus profond, d'autres questions se poseront plus tard.

Thanks!

**Comment by tchapi** [comment]
Avec plaisir !

Le temps est toujours le facteur limitant mais je suis partant pour regarder les PR, les issues, en tester quelques-unes et faire le tri là-dedans, autant que faire se peut. J'ai au moins un projet sur Sf5 / EA3 en développement actif donc qui peut me permettre de tester rapidement les choses.

A disposition

**Comment by tchapi** [comment]
J'ai bien accès à l'org **a2lix**, merci ! — en revanche pas aux repos (dont celui-là). Comment veux-tu procéder ? Je te fais une liste des PR qui sont intéressantes, je te taggue là où il y a besoin que tu approuves / merges ?

**Comment by webda2l** [comment]
Merci de ta collaboration, j'ai fixé les droits.
On peut continuer de discuter sur https://github.com/orgs/a2lix/teams/main
