### ISSUE TITLE
php8 and php8.1 support

### ISSUE THREAD

**Issue by wdrupal** [a2lix/TranslationFormBundle#370]
As the package has Symfony 6 support it would be nice to have PHP ^8 support
```
  Problem 1
    - a2lix/auto-form-bundle[0.2, ..., 0.3] require php ^7.1.3 -> your php version (8.1.1) does not satisfy that requirement.
    - a2lix/auto-form-bundle 0.3.1 requires php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - a2lix/auto-form-bundle[0.3.2, ..., 0.3.3] require symfony/config ^3.4.30|^4.3|^5.0 -> found symfony/config[v3.4.30, ..., v3.4.47, v4.3.0, ..., v4.4.36, v5.0.0, ..., v5.4.2] but the package is fixed to v6.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - a2lix/translation-form-bundle 3.1.0 requires a2lix/auto-form-bundle ^0.2|^0.3 -> satisfiable by a2lix/auto-form-bundle[0.2, ..., 0.3.3].
    - Root composer.json requires a2lix/translation-form-bundle ^3.1 -> satisfiable by a2lix/translation-form-bundle[3.1.0].


```

**Comment by tchapi** [comment]
Hi

Thanks for the report. From what I understand, it's the `auto-form-bundle` package that needs to bump its requirement and allow PHP8.0+ / Symfony6.0+ too ..

@webda2l Am I looking in the right direction ?

**Comment by wdrupal** [comment]
> Hi
> 
> Thanks for the report. From what I understand, it's the `auto-form-bundle` package that needs to bump its requirement and allow PHP8.0+ / Symfony6.0+ too ..
> 
> @webda2l Am I looking in the right direction ?

Actually that means that Symfony 6 isn't supported even if PHP is ^7

**Comment by tchapi** [comment]
I can try tomorrow maybe !

**Comment by tchapi** [comment]
The PR for **CI fixes** (_a pre-requisite to fix the dependency graph_) is [here](https://github.com/a2lix/AutoFormBundle/pull/28) for reference

**Comment by tchapi** [comment]
See https://github.com/a2lix/AutoFormBundle/pull/29

**Comment by tchapi** [comment]
Hi @wdrupal 
PR has been merged on master — Could you try again with requiring `auto-form-bundle@dev-master` ? If this works, we can create a new release on the AutoForm repository

**Comment by wdrupal** [comment]
Hi @tchapi 

It works well for me
![image](https://user-images.githubusercontent.com/4435319/149467691-a8e568a0-5b2f-4448-89c3-4848e869f7ac.png)

**Comment by tchapi** [comment]
Superb! I'll tag that right away (in a few hours)

**Comment by tchapi** [comment]
Fixed in https://github.com/a2lix/AutoFormBundle/releases/tag/0.4.0
