### ISSUE TITLE
Translatable file upload

### ISSUE THREAD

**Issue by nicolaskern** [a2lix/TranslationFormBundle#62]
Hi,

In the screenshot of your documentation, you show a translatable file upload, do you have any exemple of how to make it?

Thanks,
Nicolas

**Comment by openc0der** [comment]
@nicolaskern have you written any other file than Product, ProductTranslation and the admingenerator to make this work? I have the same issue but it's not saving the file, I only get the /tmp/fhgfhfhhfsd.
Thanks

**Comment by nicolaskern** [comment]
It's quite old, I don't remember what I had done back then...
But I think this is an usual file upload, you have to manage it yourself, what do you think?
