### ISSUE TITLE
Notice: Undefined index: translationClass A2lix/TranslationFormBundle/TranslationForm/GedmoTranslationForm.php

### ISSUE THREAD

**Issue by ghost** [a2lix/TranslationFormBundle#68]
In Sonata admin panel I got an error:

``` php
Notice: Undefined index: translationClass in /var/www/.../vendor/a2lix/translation-form-bundle/A2lix/TranslationFormBundle/TranslationForm/GedmoTranslationForm.php line 57
```

my Admin class:

``` php
 $formMapper
    ->add('translations', 'a2lix_translations_gedmo', array(
        'translatable_class' => 'Ticket\Bundle\FrontendBundle\Entity\Event',
        'fields' => array(
            'title' => array(
                'type' => 'text'
            ),
            'description' => array(
                'type' => 'textarea'
            )
        )
    ))
;
```

**Comment by daichihaji** [comment]
Hi I hit the quite the same problem with @proph7 

and now I am trying to introduce gedmo wip2.4.0  suggested by iprophet.

however stof/doctrine-extensions-bundle requires gedmo 2.3.*

these are my current setting
		"a2lix/translation-form-bundle": "1.3",	
  		"stof/doctrine-extensions-bundle" :  "dev-master",
  		 "gedmo/doctrine-extensions":      "2.3.12",

even latest stof/doctrine-extensions-bundle doesnt accept gedmo wip 2.4.0
