### ISSUE TITLE
default translation gets lost when resaving the entity

### ISSUE THREAD

**Issue by craue** [a2lix/TranslationFormBundle#78]
I'm using Gedmo's personal translations with enabled persistence of default translations. My default locale is `de` and the additional locale is `en`. When persisting a new entity with a translatable `title` field, both translations are saved correctly. But when editing this entity (using the same form type) without changing any values, the default title translation is set to `null` in the database after submitting the form.

When editing again, I can set a new title value which is then saved correctly.

But then, when editing and just submitting the form with its current values, the default title translation is lost again.

Any idea what's wrong there?

**Comment by Rvanlaak** [comment]
I see what is going wrong here. My application uses the following code (simplified) and is using the KnpLabs traits behaviour:
```php
foreach (['nl', 'en', 'de'] as $lang) {
    $variable->translate($lang)->setValue($postValue);
}
```
When I submit an empty value for the German translation, it does fall back to the default language which is `en`. The result of this is that the `en` translation gets overwritten by the `de` value.

The following commit solves this unwanted behaviour https://github.com/KnpLabs/DoctrineBehaviors/commit/8077613800c87e0119fe6734f463c245e4dd5f97
