### ISSUE TITLE
How to handle collection

### ISSUE THREAD

**Issue by montabou** [a2lix/TranslationFormBundle#81]
I don't know why but I can not use collection using a2lix forms. I've tried using a2lix_translations but I was not able to find correct options. So I've created a new form type to use with a2lix_translationsForms but I've got this error:

```
 The form's view data is expected to be of type scalar, array or an instance of 
\ArrayAccess, but is an instance of class MyClass. You can avoid this error by 
setting the "data_class" option to "MyClass" or by adding a view transformer that 
transforms an instance of class MyClass to scalar, array or an instance of 
\ArrayAccess
```

and when I add data_class, I've got:

```
The form's view data is expected to be an instance of class MyClass, but is an 
instance of class Doctrine\ORM\PersistentCollection. You can avoid this error by 
setting the "data_class" option to null or by adding a view transformer that 
transforms an instance of class Doctrine\ORM\PersistentCollection to an instance 
of MyClass
```

The problem occurs when I try to edit an entity that I've created manually. For creation the form is generated when removing the data_class option but the entity does not persist into database.

I'm using admin2generator so I do not write edittype manually. I've tried all options I was able to find but nothing works.

**Comment by anacicconi** [comment]
I'm having exactly the same problem with a form that has another embedded form. Both entities are related by an OneToOne reference as I explained on this issue: #207

Does anybody know why? Thanks!
